### ISSUE TITLE
How do I rename a published crate

### ISSUE THREAD

**Issue by Alfriadox** [rust-lang/crates.io#2618] opened 2020-07-09 21:01 UTC
I accidentally published a crate under the name "Linguist" (I meant to write "linguist"). I yanked it immediately and it has no downloads/dependencies. Is there anyway to rename this crate?

**Comment by ehuss** [comment] 2020-07-09 21:05
Transferred to crates.io issue tracker.

**Comment by carols10cents** [comment] 2020-07-10 01:28
Not at this time, no. This is a duplicate of https://github.com/rust-lang/crates.io/issues/1451.

**Closed by carols10cents** 2020-07-10 01:28 UTC
