### ISSUE TITLE
Skipped chess v0.1.1

### ISSUE THREAD

**Issue by jordanbray** [rust-lang/crates.io#345] opened 2016-05-28 21:31 UTC
Somehow, when I did a cargo publish, the package was not available for download.

The crates.io website showed the update, but the https://github.com/rust-lang/crates.io-index/commits/master commit log did not have an associated version.

I waited 20 minutes before attempting anything, meanwhile other commits did show up in that log.

I updated te 0.1.2 to see if it would fix it, and it did.

**Comment by alexcrichton** [comment] 2016-05-31 03:37
Sounds suspicious! It could be the case that something went wrong with an uploaded and some transaction wasn't correctly rolled back. Definitely seems fishy...

**Comment by carols10cents** [comment] 2016-12-15 13:46
There's slightly more detail on #448, and these describe the same symptoms, so I'm going to close this one as a duplicate of #448.

**Closed by carols10cents** 2016-12-15 13:46 UTC
