### ISSUE TITLE
doc.crates.io no HTTPS

### ISSUE THREAD

**Issue by TomasHubelbauer** [rust-lang/crates.io#1139] opened 2017-10-20 19:38 UTC
While crates.io seem to support HTTPS (and do upgrade HTTP requests to it), doc.crates.io doesn't and thus doesn't, respectively. This displays *Not secure* in Google Chrome 62.

**Comment by carols10cents** [comment] 2017-10-20 20:03
Yep, this is a duplicate of https://github.com/rust-lang/crates.io/issues/621. Currently, doc.crates.io is hosted on github pages, so we're unable to use a custom domain+SSL.

In the near future, we will be switching to serving cargo docs from https://doc.rust-lang.org/cargo, and we will have SSL configured there. You can track the progress of that effort at https://github.com/rust-lang/rust/issues/44910. 

In the meantime, the workaround is to visit http://doc.crates.io instead. Thank you for your patience!

**Closed by carols10cents** 2017-10-20 20:03 UTC
