### ISSUE TITLE
Dark Mode: Links without href are black on dark grey

### ISSUE THREAD

**Issue by paul-hansen** [rust-lang/crates.io#9330] opened 2024-08-24 16:28 UTC
### Current Behavior

Links in dark mode if they don't have an href (e.g. `[sometext](notactuallyalink)`) are hard to read due to them being black and the background is dark gray so there is very little contrast between them.
Example:
https://crates.io/crates/glycin/1.0.2
![image](https://github.com/user-attachments/assets/b7159116-bd12-4364-b9de-6b99fb6b969d)
Source code of the readme https://gitlab.gnome.org/sophie-h/glycin/-/raw/1.0.1/README.md

### Expected Behavior

Expected there to be more contrast between the background color and the color of links.

### Steps To Reproduce

1. go to https://crates.io/crates/glycin
2. observe the links on page

### Environment

- Browser: Firefox
- OS: EndeavorOS (Arch based rolling distro)

### Anything else?

Originally I didn't realize this was caused by their readme not having valid links. Not as big of a deal as I originally thought, probably still good to fix the color on invalid links though.

**Comment by Turbo87** [comment] 2024-08-24 16:33
this appears to be caused by these anchor tags not having an `href` attribute. https://docs.rs/crate/glycin/1.0.2/source/README.md shows that in the latest release of the project these links don't appear to link anywhere, which is causing the links to show up with the wrong color. in the `main` branch in the repository these seem to be fixed, so most likely this issue will already be fixed with the next release of that crate.

**Comment by Turbo87** [comment] 2024-08-24 16:39
to be clear: it's still a bug that these show up as black instead of the regular text color, just one that is an unfortunate edge case uncovered by the bug in that readme 😉

**Comment by paul-hansen** [comment] 2024-08-24 16:43
Good catch! I totally missed that. I updated the description and post to reflect that. Thanks!

**Closed** 2024-08-27 08:39 UTC
Labels: C-bug 🐞, A-frontend 🐹
