### ISSUE TITLE
Please make are mirror crates.io

### ISSUE THREAD

**Issue by sinitcin** [rust-lang/crates.io#1403] opened 2018-05-24 14:58 UTC
Hello! In my country government make are block list of IP. And my internet provider block crates.io =( 

Please help me!

**Comment by Rafagd** [comment] 2018-06-05 19:29
Not sure if this solves your problem, but I saw this link earlier today and it just might: http://www.integer32.com/2016/10/08/bare-minimum-crates-io-mirror-plus-one.html

**Comment by sinitcin** [comment] 2018-06-06 09:48
Oh, thank you! I get try =) 

На 5 июня 2018 г., 22:29, в 22:29, "Rafael G. Dantas" <notifications@github.com> написал:п>Not sure if this solves your problem, but I saw this link earlier today

**Comment by carols10cents** [comment] 2019-10-09 14:14
I'm going to close this as a duplicate of #67.

**Closed by carols10cents** 2019-10-09 14:14 UTC
Labels: C-feature-request, T-infra, WG-infra-crates.io, infrastructure
