### ISSUE TITLE
crate page should show the latest non-yanked version if any

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang/crates.io#260] opened 2016-02-02 00:49 UTC
Right now, the `toml` crate's latest version (0.1.26) is yanked, but the [crate page](https://crates.io/crates/toml) says the *crate* has been yanked. However, the [version page for 0.1.25](https://crates.io/crates/toml/0.1.25) shows happily shows up.

This is unexpected!

**Comment by alexcrichton** [comment] 2016-02-02 00:51
Dupe of https://github.com/rust-lang/crates.io/issues/76, but thanks for teh report!

**Closed by alexcrichton** 2016-02-02 00:51 UTC
