### ISSUE TITLE
Inconsistent installation instructions for binaries

### ISSUE THREAD

**Issue by ReagentX** [rust-lang/crates.io#8819] opened 2024-06-09 21:19 UTC
### Current Behavior

 I have gotten several reports of users being confused about the inconsistent installation instructions for binaries on crates.io:

<img width="955" alt="Screenshot 2024-06-09 at 2 16 01 PM" src="https://github.com/rust-lang/crates.io/assets/1920666/30a338e5-c348-4975-906f-0aea64e9fe7d">

The current behavior incorrectly displays the `cargo add` command, even though this is a binary and not a library: https://crates.io/crates/imessage-exporter

### Expected Behavior

The install column should show `cargo install` instead of `cargo add` for creates that are only binaries and not libraries.

### Steps To Reproduce

1. Navigate to https://crates.io/crates/imessage-exporter

### Environment

- Browser: Safari Version 17.5 (19618.2.12.11.6)
- OS: macOS Sonoma 14.5 (23F79)

**Comment by Turbo87** [comment] 2024-06-10 14:17
this is a duplicate of https://github.com/rust-lang/crates.io/issues/5882

**Closed by Turbo87** 2024-06-10 14:17 UTC
