### ISSUE TITLE
Opening crate with latest yanked version from search leads to yanked version itself

### ISSUE THREAD

**Issue by DoumanAsh** [rust-lang/crates.io#1156] opened 2017-10-31 17:00 UTC
If you go look for `quickcheck` which currently has latest version 0.4.2 yanked https://crates.io/search?q=quickcheck and try to access it by just clicking you get a yanked version.

But if instead you go to direct link you'll get 0.4.1 https://crates.io/crates/quickcheck

Would be nice to align the behavior(preferably if search would lead to latest non-yanked version)

**Comment by Majora320** [comment] 2017-11-20 05:00
Same for one of my crates (steamid-ng). Would really love for this to get fixed.

**Comment by carols10cents** [comment] 2018-06-28 16:37
Closing as a duplicate of #510. Thanks!

**Closed by carols10cents** 2018-06-28 16:37 UTC
