### ISSUE TITLE
Use the lowest dependency versions when publishing

### ISSUE THREAD

**Issue by kvark** [rust-lang/crates.io#1145] opened 2017-10-24 18:24 UTC
Currently, when doing `cargo publish` it tries to build the project from scratch, downloading all the latest dependencies fulfilling the semantic version requirements. For example, having `futures = "0.1"` would fetch version "0.1.16" to test the build before publishing. This is a problem because the current crate may depend on some extra stuff added between, say, "0.1.12" and "0.1.16" but doesn't reflect that properly in the cargo configuration. The users having an earlier version in the `Cargo.lock` may get a broken build then (that sometimes can be solved by `cargo update -p futures`).

There is a simple thing `cargo` could do to enforce the minimum dependency versions: pick the minimally compatible version for building when publishing. Thus, if one dependency needs "0.1.12" and another needs "0.1", `cargo publish` should try building with "0.1.12" instead of taking the latest.

**Comment by carols10cents** [comment] 2017-10-24 20:27
We actually had the same thought as part of the public/private dependencies RFC; I'm pretty sure https://github.com/rust-lang/cargo/issues/4100 is a duplicate of this issue so I'm going to close this one. Let me know if I'm missing anything!

**Closed by carols10cents** 2017-10-24 20:27 UTC

**Comment by kvark** [comment] 2017-10-25 01:14
Thanks @carols10cents ! I searched the bug list but somehow missed it.
