### ISSUE TITLE
Should publishes with versions only differing in metadata be allowed?

### ISSUE THREAD

**Issue by sfackler** [rust-lang/crates.io#1059] opened 2017-09-15 21:21 UTC
For example, https://crates.io/crates/openssl-src has `110.0.0` and `110.0.0+1.1.0f`, which are semver-equivalent since build metadata doesn't affect the actual version. It seems like this probably shouldn't be allowed?

**Comment by mbrubeck** [comment] 2017-09-15 21:24
Some previous discussion in https://github.com/steveklabnik/semver/issues/107

**Comment by carols10cents** [comment] 2017-09-20 17:55
Sure sounds like we should be disallowing versions like these that only differ in build metadata....

**Comment by jeikabu** [comment] 2018-12-06 03:02
Looks like I fell victim to this.

I'd been using semver metadata only to [discover it doesn't work as expected](https://crates.io/crates/runng-sys/versions).  Rather than getting rid of metadata support it would make sense to let them be semver equivalent.  Whether some attempt is made to parse and make sense of the metadata is a convention that could be developed separately.  Until then taking the most recent would be the "least surprising".

To me the primary use case is crates that have some external, non-crate dependency and you want to mirror it's semver version.  "sys" crates fall in this category.  I have a crate that corresponds to NNG `1.1.1`.  Being able to version my crate as `1.1.1` instead of some unrelated version scheme that requires mapping between the two is the simplest.  If I need to alter crate contents in some way (e.g. packaging or documentation- some non-API-breaking change) `1.1.1+SOMETHING` would make the most sense.

As it is, if you have a crate versioned `0.1.0+XYZ` and you then publish/yank `0.1.0` [the crate is "yanked"](https://crates.io/crates/cargo_crates-io_docs-rs_test) even when there's a [semver-equivalent crate available](https://crates.io/crates/cargo_crates-io_docs-rs_test/versions), `0.1.0+3`.

**Comment by sgrif** [comment] 2019-08-15 19:12
I really do think this just boils down to a bug in semver. Build metadata is ignored for precedence, but that does not mean it's ignored for equality. To me this implies that if two versions differ only in metadata, we may select one at random to treat as the "latest version", but they are still *different* versions, and should be treated as such both by crates.io and Cargo. I laid out some further reasoning in https://github.com/steveklabnik/semver/issues/107#issuecomment-521760730

**Comment by pietroalbini** [comment] 2019-08-15 20:34
The ordering being the same is not going to be changed as far as I can see, and that makes any possible use of releases with the same version but different metadata practically impossible.

If the contents of the two releases with different metadata are the same there is not really a point of having two releases, and if it's different users that don't check specifically for either version are going to get a *random* release, which is plain bad and unexpected for everyone.

Based on that I'd like to see publishing releases with the same version but different metadata blocked on new uploads, regardless of what Cargo does. Blocking metadata completly is not needed, as there are still valid uses for it (for example the `google-*` crates use metadata to let users know at a glance when the bindings were automatically generated).

Maybe we should look for active crates that are consistently using metadata today and ask them for feeback?

**Comment by jackgerrits** [comment] 2020-01-30 00:35
I've just hit this, I have a sys crate and the version tracks the version of the bound library. I had to do a follow up release to fix an issue with the docs.rs build. I am not able to increment the version number as then the versions would be out of sync. I used the metadata to indicate it was an updated version. However, now I am not able to depend on the lib:
```
error: failed to verify the checksum of `vowpalwabbit-sys v8.8.0`
```

I tried yanking the original versions and only kept the latest post release but this did not seem to help.

**Comment by jtgeibel** [comment] 2020-01-30 02:47
@jackgerrits So I don't think this is a long-term solution, but I have an idea of something that may be interesting to test.  Would you try pushing several versions of your crate to staging.crates.io in the **opposite order**?

It would be interesting to see what happens server and client side.  In particular, I expect that cargo will pick the first matching row in the index, and that by publishing `+post3` first cargo will always grab it.  It's probably still not possible to access the other versions, but at least it would give us a way to modify the index without really removing any metadata tracked by the index.

So that's my short term idea.  We could reorder the lines in the index, an act that in theory is a noop but in practice will hopefully fix things for your crate.  A bit longer term, we could error or warn in cargo when using a `+`.  But in your case, any such warning would be too late, as you had already published `8.8.0`.  Long term, I'm not really sure what the solution is.  I haven't yet had a chance to re-read this thread and the linked semver thread.

**Comment by carols10cents** [comment] 2020-01-31 15:20
I'm going to lay out my current thoughts of what the actual behavior of interacting with build metadata *should* be, ideally:

1. Publishing of crate versions that differ only in build metadata should be allowed, to support the sys crate use case. That is, I should be able to publish `a-sys v1.0.0-whatever` and `a-sys v1.0.0-somethingelse`.

2. When Cargo.lock contains a version with build metadata, it should always download the exact same version, including the same build metadata. That is, if I have a Cargo.lock that contains `a-sys v1.0.0-whatever`, I should always get `a-sys v1.0.0-whatever` even if `a-sys v1.0.0-somethingelse` also exists.

3. When Cargo is resolving versions from Cargo.toml without a Cargo.lock or when doing a `cargo update`, if a version is specified with build metadata in Cargo.toml it should always get that exact version? That is, if I specify `a-sys = { version = "1.0.0-whatever" }`, I should always get exactly 1.0.0-whatever? (I'm not sure this is expected behavior or not, I could also see expecting the behavior in the next item)

4. When Cargo is resolving versions from Cargo.toml without a Cargo.lock or when doing a `cargo update`, if a version is specified WITHOUT build metadata in Cargo.toml it should always get the semver compatible version published most recently. That is, if I specify `a = { version = "1.0.0" }` and `a-sys v1.0.0-whatever` was published and then `a-sys v1.0.0-somethingelse` was published, I should always get `a-sys v1.0.0-somethingelse`.

I think the biggest problem right now is that 2. is not happening, as detailed in https://github.com/rust-lang/cargo/issues/7180. I don't think this is a problem in crates.io, it's only a problem in cargo.

So I think this issue can be closed because the answer to the title is "yes, publishes with versions only differing in metadata should be allowed".

Am I missing anything?

**Comment by carols10cents** [comment] 2020-01-31 16:07
When we discussed this in the crates.io team meeting, we were wondering what other package managers do. I just tested npm, and it strips build metadata completely on publish.

Experiment 1:

- Publish a package with version 1.0.0
- Attempt to publish version 1.0.0+something
- Publish is rejected because `+something` is removed and `1.0.0` already exists

Experiment 2:

- Publish a package with version 1.0.1+something
- Publish succeeds with version 1.0.1 because `+something` is removed

https://www.npmjs.com/package/@carols10cents/foo

**Comment by carols10cents** [comment] 2020-01-31 16:16
Rubygems doesn't support specifying build metadata at all: https://github.com/rubygems/bundler/issues/6972

**Comment by ehuss** [comment] 2020-01-31 18:53
Overall, I think my preference would be to have crates.io not allow multiple versions that differ only in metadata.  Whether or not the metadata is displayed on crates.io is another question, though I don't know if it matters too much.

----
Some other behaviors:

NuGet seems to display, but otherwise ignore metadata (https://github.com/NuGet/Home/wiki/SemVer-2.0.0-support#package-identity).

Go modules seem to mostly ignore metadata?  When I use a requirement with metadata, it just seems to get removed.

Julia's Pkg doesn't error, but it looks like it might randomly pick based on metadata (or the latest one?).  Regardless, it does not appear to be working correctly.

Python doesn't follow semver, but has a similar concept (https://www.python.org/dev/peps/pep-0440/#local-version-identifiers).  They are not intended for public repositories, and it looks like cannot be used in a "version specifier" (semver version requirement).

**Comment by sgrif** [comment] 2020-01-31 19:40
I can certainly see why so many other package managers would ignore or forbid metadata, since it could definitely cause problems based on the semver spec

> Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

This implies that if versions `1.0.0`, `1.0.0+foo` and `1.0.0+bar` exist, the versionreq `1.0.0` can match any of them. The spec is unfortunately never mentions metadata WRT equality, but I would assume that defaults to two versions with differing metadata are not equal.

If we do decide to forbid publishing versions that differ only in metadata, we still have the issue of what should we do with those versions that exist today?

**Comment by dwijnand** [comment] 2020-01-31 20:10
> The spec is unfortunately never mentions metadata WRT equality, but I would assume that defaults to two versions with differing metadata are not equal.

We explored this in https://github.com/steveklabnik/semver/issues/108#issuecomment-521897850 😄 

> I have a sys crate and the version tracks the version of the bound library. I had to do a follow up release to fix an issue with the docs.rs build. I am not able to increment the version number as then the versions would be out of sync. I used the metadata to indicate it was an updated version. However, now I am not able to depend on the lib

Btw, the closest thing to an "official" answer about this use case is:

> how transitive dependencies are tracked is a matter for tooling, not semver. Semver provides a standard means for labeling nodes in a dependency graph, not how to mange the entire graph.

(https://github.com/semver/semver/issues/169#issuecomment-427710518)

😕

**Comment by Turbo87** [comment] 2023-05-23 13:27
I've played around a bit with the database dump and came up with a query to find versions in the database with the same version number but conflicting build metadata:

```sql
SELECT crates.name, split_part(num, '+', 1) as num_no_build, COUNT(num) as count
FROM versions
LEFT JOIN crates ON crate_id = crates.id
WHERE position('+' in num) != 0
GROUP BY crates.name, num_no_build
HAVING COUNT(num) > 1
ORDER BY COUNT(num) DESC, crates.name, num_no_build;
```

This results in 614 problematic versions, spread out across 261 crates.

<details>
    <summary>List of all crates with conflicting versions:</summary>
    
- almel: 1
- async-sea-orm-session: 1
- boomphf-patched: 1
- cargo_crates-io_docs-rs_test: 1
- chromaprint-sys-next: 1
- cifra: 2
- ckb-system-scripts: 1
- cursed-trying-to-break-cargo: 1
- eddn: 1
- elite_journal: 1
- fbthrift-git: 1
- ffav-sys: 1
- flatc: 1
- gerb: 1
- googapis: 3
- google-abusiveexperiencereport1: 1
- google-acceleratedmobilepageurl1: 1
- google-adexchangebuyer1d3: 6
- google-adexchangebuyer1d3-cli: 3
- google-adexchangebuyer1d4: 5
- google-adexchangebuyer1d4-cli: 2
- google-adexchangebuyer2_v2_beta1: 1
- google-adexchangeseller2: 3
- google-adexperiencereport1: 2
- google-admin1_directory: 6
- google-admin1_directory-cli: 1
- google-admin1_reports: 5
- google-admin1_reports-cli: 2
- google-adsense1d4: 6
- google-adsense1d4-cli: 3
- google-adsensehost4d1: 6
- google-adsensehost4d1-cli: 3
- google-analytics3: 6
- google-analytics3-cli: 2
- google-analyticsreporting4: 1
- google-androiddeviceprovisioning1: 2
- google-androidenterprise1: 6
- google-androidenterprise1-cli: 1
- google-androidmanagement1: 2
- google-androidpublisher2: 6
- google-androidpublisher2-cli: 2
- google-appengine1: 4
- google-appengine1-cli: 1
- google-appengine1_beta4: 5
- google-appengine1_beta4-cli: 2
- google-appengine1_beta5: 5
- google-appengine1_beta5-cli: 2
- google-appsactivity1: 5
- google-appsactivity1-cli: 3
- google-appstate1: 6
- google-appstate1-cli: 3
- google-bigquery2: 6
- google-bigquery2-cli: 1
- google-bigquerydatatransfer1: 2
- google-books1: 5
- google-books1-cli: 1
- google-calendar3: 6
- google-calendar3-cli: 3
- google-civicinfo2: 2
- google-classroom1: 5
- google-cloudbilling1: 3
- google-cloudbilling1-cli: 1
- google-cloudbuild1: 1
- google-clouddebugger2: 4
- google-clouddebugger2-cli: 2
- google-clouderrorreporting1_beta1: 1
- google-cloudfunctions1: 2
- google-cloudiot1: 1
- google-cloudkms1: 2
- google-cloudmonitoring2_beta2: 4
- google-cloudmonitoring2_beta2-cli: 2
- google-cloudresourcemanager1: 5
- google-cloudresourcemanager1-cli: 1
- google-cloudresourcemanager1_beta1: 6
- google-cloudresourcemanager1_beta1-cli: 2
- google-cloudtasks2_beta2: 2
- google-cloudtrace1: 2
- google-cloudtrace2: 1
- google-compute1: 2
- google-container1: 4
- google-container1_beta1: 1
- google-content2: 6
- google-content2-cli: 1
- google-content2_sandbox: 5
- google-content2_sandbox-cli: 3
- google-coordinate1: 1
- google-customsearch1: 3
- google-customsearch1-cli: 1
- google-dataproc1: 5
- google-dataproc1-cli: 1
- google-datastore1: 1
- google-datastore1_beta2: 1
- google-datastore1_beta3: 1
- google-deploymentmanager2: 5
- google-deploymentmanager2-cli: 2
- google-deploymentmanager2_beta2: 1
- google-dfareporting2d1: 1
- google-dfareporting2d2: 1
- google-dfareporting2d3: 1
- google-dfareporting2d4: 1
- google-dfareporting2d5: 2
- google-dfareporting2d5-cli: 2
- google-dfareporting2d6: 2
- google-dfareporting2d6-cli: 2
- google-dfareporting2d7: 2
- google-dfareporting2d7-cli: 2
- google-dfareporting2d8: 2
- google-dfareporting3: 1
- google-dialogflow2_beta1: 1
- google-discovery1: 1
- google-dlp2_beta1: 1
- google-dns1: 6
- google-dns1-cli: 3
- google-doubleclickbidmanager1: 6
- google-doubleclickbidmanager1-cli: 1
- google-doubleclicksearch2: 6
- google-doubleclicksearch2-cli: 3
- google-drive2: 6
- google-drive2-cli: 1
- google-drive3: 6
- google-drive3-cli: 1
- google-fcm1: 1
- google-firebasedynamiclinks1: 3
- google-firebasedynamiclinks1-cli: 1
- google-firebaseremoteconfig1: 1
- google-firestore1_beta1: 1
- google-fitness1: 3
- google-fitness1-cli: 1
- google-freebase1: 1
- google-fusiontables2: 3
- google-fusiontables2-cli: 1
- google-games1: 6
- google-games1-cli: 3
- google-gamesconfiguration1_configuration: 6
- google-gamesconfiguration1_configuration-cli: 3
- google-gamesmanagement1_management: 6
- google-gamesmanagement1_management-cli: 3
- google-genomics1: 6
- google-genomics1-cli: 3
- google-gmail1: 5
- google-gmail1-cli: 1
- google-groupsmigration1: 2
- google-groupsmigration1-cli: 1
- google-groupssettings1: 3
- google-groupssettings1-cli: 1
- google-iam1: 4
- google-identitytoolkit3: 6
- google-identitytoolkit3-cli: 1
- google-kgsearch1-cli: 1
- google-language1: 1
- google-language1_beta1: 1
- google-licensing1: 1
- google-licensing1-cli: 1
- google-logging1_beta3: 1
- google-logging2: 3
- google-logging2-cli: 1
- google-logging2_beta1: 4
- google-logging2_beta1-cli: 1
- google-manufacturers1: 3
- google-manufacturers1-cli: 1
- google-mirror1: 4
- google-mirror1-cli: 1
- google-ml1: 2
- google-ml1_beta1: 1
- google-monitoring3: 5
- google-monitoring3-cli: 3
- google-oauth2_v2: 1
- google-oslogin1: 1
- google-oslogin1_beta: 2
- google-pagespeedonline2: 3
- google-pagespeedonline2-cli: 1
- google-partners2: 3
- google-partners2-cli: 1
- google-people1: 3
- google-playmoviespartner1: 3
- google-playmoviespartner1-cli: 2
- google-plus1: 6
- google-plus1-cli: 3
- google-plusdomains1: 6
- google-plusdomains1-cli: 3
- google-prediction1d6: 1
- google-proximitybeacon1_beta1: 4
- google-proximitybeacon1_beta1-cli: 1
- google-pubsub1: 4
- google-pubsub1-cli: 2
- google-pubsub1_beta2: 5
- google-pubsub1_beta2-cli: 3
- google-qpxexpress1: 1
- google-replicapool1_beta2: 1
- google-replicapoolupdater1_beta1: 2
- google-replicapoolupdater1_beta1-cli: 1
- google-resourceviews1_beta2: 1
- google-runtimeconfig1: 1
- google-runtimeconfig1_beta1: 1
- google-safebrowsing4: 3
- google-safebrowsing4-cli: 1
- google-searchconsole1: 2
- google-searchconsole1-cli: 1
- google-servicecontrol1: 1
- google-sheets4: 1
- google-siteverification1: 3
- google-siteverification1-cli: 1
- google-sourcerepo1: 2
- google-spanner1: 2
- google-spectrum1_explorer: 4
- google-spectrum1_explorer-cli: 2
- google-speech1: 1
- google-speech1_beta1: 1
- google-sqladmin1_beta4: 6
- google-sqladmin1_beta4-cli: 1
- google-storage1: 6
- google-storage1-cli: 1
- google-storagetransfer1: 3
- google-storagetransfer1-cli: 2
- google-surveys2: 2
- google-surveys2-cli: 1
- google-tagmanager1: 2
- google-tagmanager2: 1
- google-taskqueue1_beta2: 1
- google-testing1: 2
- google-tpu1_alpha1: 1
- google-translate2: 2
- google-vault1: 2
- google-videointelligence1_beta1: 1
- google-vision1: 1
- google-webmasters3: 4
- google-webmasters3-cli: 2
- google-youtube3: 7
- google-youtubeanalytics1: 6
- google-youtubeanalytics1-cli: 2
- google-youtubereporting1: 4
- google-youtubereporting1-cli: 2
- jpegxl-rs: 1
- jpegxl-sys: 1
- knet-bindings: 1
- libaeron-sys: 1
- libaeron_driver-sys: 1
- libbpf-sys: 1
- lightpanel: 1
- lnpbp: 2
- lnpbp_derive: 1
- lnpbp_services: 1
- lz4-sys: 1
- mylibrary: 1
- opencc-sys: 1
- qpl: 1
- router-bridge: 1
- runng: 1
- runng-sys: 2
- sep-sys: 1
- serum-borsh: 1
- solana-accountsdb-plugin-kafka: 1
- spdlog-src: 2
- spng: 1
- spng-sys: 1
- strict_encoding: 1
- thinker: 3
- tonic_datastore_v1: 1
- vowpalwabbit-sys: 1
- zabrze: 1
- zeromq-src: 1
</details>

**Closed** 2023-05-30 10:14 UTC
Labels: C-bug 🐞, A-backend ⚙️

**Comment by Turbo87** [comment] 2023-05-30 10:37
https://github.com/rust-lang/crates.io/pull/6518 has now been deployed. in other words: crates.io no longer allows "publishes with versions only differing in metadata"

we are keeping the existing versions for now, simply because we haven't yet decided what to do with them. given that cargo is not able to handle them properly it might be best to delete them, but we will need consensus among the team(s) and potentially crate owners before moving forward with something like that.
