### ISSUE TITLE
Support Org READMEs

### ISSUE THREAD

**Issue by dpbriggs** [rust-lang/crates.io#1885] opened 2019-11-07 04:56 UTC
Hey, do you think it's a good idea to support org file READMEs?

For example, [this crate](https://crates.io/crates/growable-bloom-filter) is a bit off-putting because of the text format. It would be nice to render the org file as html.

I have written org file handling using the excellent [orgize](https://crates.io/crates/orgize/0.4.0) library here:

https://github.com/rust-lang/crates.io/compare/master...dpbriggs:org-mode-handling

Still need to write tests :p but could open a PR. What do you think?

Before:

![old-crates](https://user-images.githubusercontent.com/5560032/68360873-86a23480-00d6-11ea-8dcc-72e5d20d3295.png)

Rendered:

![growable-bloom-filters](https://user-images.githubusercontent.com/5560032/68360874-8bff7f00-00d6-11ea-8962-1251f70bd286.png)

**Comment by carols10cents** [comment] 2019-11-07 18:53
I think I'd prefer what was suggested in https://github.com/rust-lang/crates.io/issues/1223 which is to use pandoc to support even more markup languages like  rst and tex too. Would you be interested in working on integrating pandoc?

As such, I'm going to close this as a duplicate of #1223. Thanks!

**Closed by carols10cents** 2019-11-07 18:54 UTC
