### ISSUE TITLE
Add API functionality to query if a crate was published to completion

### ISSUE THREAD

**Issue by sebschmi** [rust-lang/crates.io#3677] opened 2021-06-03 13:22 UTC
**Is your feature request related to a problem? Please describe.**
This is motivated by [this issue](https://github.com/sunng87/cargo-release/issues/224) in cargo-release.

cargo-release allows automated publishing of a workspace, but it runs into problems where if two interdependent crates are published too short after each other, the publish might fail.

Say e.g. crate A is to be published with version 1.0.0 and crate B is to be published with 1.0.0 as well, where crate B depends on crate A, version 1.0.0.
If we simply run cargo publish for crate A first, and then immediately after the process terminates run cargo publish for crate B, then then the publish of B might fail because crate A does not exist yet with 1.0.0.

**Describe the solution you'd like**
Instead of repeatedly trying to publish crate B until it is successful, it would be nice to be able to query crates.io for whatever condition crate A needs to fulfil to have crate B published. Alternatively it would be nice to have the API call that does the publishing only return after crate A is completely published.

**Describe alternatives you've considered**
Waiting a fixed number of seconds between publishes: Sometimes crates.io takes longer than the constant, and then the second publish still fails. When setting the constant very large, it becomes tedious to wait for publishing a few crates.
Just retrying the publish: While that likely would work, it is not a very nice solution.

**Comment by Turbo87** [comment] 2021-06-03 13:45
this seems to be a duplicate of https://github.com/rust-lang/crates.io/issues/3512

**Closed by Turbo87** 2021-06-03 13:45 UTC
