### ISSUE TITLE
Better error message when unable to load an API response

### ISSUE THREAD

**Issue by vi** [rust-lang/crates.io#735] opened 2017-05-21 23:44 UTC
Ccrate.io showed this as network went offline during searching for a crate:

```
Error while processing route: search The adapter operation was aborted t@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:9:23098
i@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:27:25796
o/r@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:27:26021
l@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:27:29170
p<.ajax/</d.error@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:28:605
pe.Callbacks/l@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:3:30998
pe.Callbacks/d.fireWith@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:3:31769
n@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:5:3488
.send/r/<@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:5:8324
  vendor-095b079d8ca6a21aaefc917754b8486f.js:11:28783
The adapter operation was aborted
t@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:9:23098
i@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:27:25796
o/r@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:27:26021
l@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:27:29170
p<.ajax/</d.error@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:28:605
pe.Callbacks/l@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:3:30998
pe.Callbacks/d.fireWith@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:3:31769
n@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:5:3488
.send/r/<@https://crates.io/assets/vendor-095b079d8ca6a21aaefc917754b8486f.js:5:8324
  vendor-095b079d8ca6a21aaefc917754b8486f.js:9:23663
```

Expected: a message like "You are offline" or "Can't contact the server".

**Comment by carols10cents** [comment] 2017-09-14 00:13
This is a duplicate of #240. Closing!

**Closed by carols10cents** 2017-09-14 00:13 UTC
Labels: A-ember, A-ui, C-bug, E-help-wanted
