### ISSUE TITLE
Errors in the browser console when navigating to an invalid crate page

### ISSUE THREAD

**Issue by ghost** [rust-lang/crates.io#576] opened 2017-02-24 18:16 UTC
When navigating to an invalid crate page, e.g. `https://crates.io/crates/foo`, some Javascript errors occur. Here's the traceback :  https://gist.github.com/Insomgla/998ec62b77d1ef4f2b7e47ac666bf71d

**Comment by locks** [comment] 2019-09-06 23:31
Duplicate of https://github.com/rust-lang/crates.io/issues/556.

**Closed by locks** 2019-09-06 23:31 UTC
Labels: A-ember, A-ui, C-bug, E-help-wanted
