### ISSUE TITLE
Display latest non-yanked version of crates

### ISSUE THREAD

**Issue by cramertj** [rust-lang/crates.io#1444] opened 2018-06-26 21:10 UTC
When selecting a crate whose latest version has been yanked, crates.io shows the message "This crate has been yanked, but it is still available for download for other crates that may be depending on it."

This page should provide a link to the last non-yanked version of the crate so that users don't have to manually search through the previous versions to find the newest non-yanked version of the crate.

**Comment by carols10cents** [comment] 2018-06-27 01:22
Closing as a duplicate of #510. Thanks!

**Closed by carols10cents** 2018-06-27 01:22 UTC
