### ISSUE TITLE
README not rendered (HTTP 403 returned)

### ISSUE THREAD

**Issue by rursprung** [rust-lang/crates.io#2729] opened 2020-08-29 08:16 UTC
the README is not rendered for my crate on crates.io: https://crates.io/crates/r2d2-oracle
the GET https://static.crates.io/readmes/r2d2-oracle/r2d2-oracle-0.3.0.html returns a HTTP 403 response.

note: the error is the same as reported in #968 but there the analysis has shown that the crate specified `include` and didn't add the `README.md` there. my crate does not specify `include`, thus it should be packaged along.

oddly enough the same is the case now for the older releases, though i'm almost certain that for 0.1.0 and 0.2.0 it used to render the README (but that was a year ago, so who knows how well my memory really is 😮), so it might be related to something which changed in the README and which the parser doesn't like? both github and IntelliJ are able to correctly render the `README.md` file.

it would be nice if there would be some (easily accessible) diagnostics somewhere telling crate owners why their README was not rendered in case it wasn't rendered. does this exist and i was just not able to find it?

**Comment by plaets** [comment] 2021-01-19 12:20
Hi, I have tested your crate on my local crates.io instance, and it seems that the Cargo.toml of your crate does not include the path to the README. [Here is the relevant part of cargo docs.](https://doc.rust-lang.org/cargo/reference/manifest.html#the-readme-field) After adding this field, the README seems to render just fine, at least under my test environment.

**Comment by rursprung** [comment] 2021-01-21 14:44
thanks for looking into this. but according to the documentation that should not be needed. from the page which you linked:
> If no value is specified for this field, and a file named `README.md`, `README.txt` or `README` exists in the package root, then the name of that file will be used.

**Comment by plaets** [comment] 2021-01-21 18:47
Sorry, you are right, I missed that part. 
Turns out the issue is more complicated than I thought. Your actually crate actually works fine with local uploader configured, I just forgot to setup the background worker. 
Maybe the problem is related to S3, but I'm not sure.

**Comment by plaets** [comment] 2021-01-22 14:05
I have just published a test crate with a readme file but without the readme field in Cargo.toml and it seems to work fine...
<https://crates.io/crates/test-mueQu9Oz>
(sorry for littering, I'm ok with this crate getting removed in the future, nothing depends on it)
I used [cargo-download](https://crates.io/crates/cargo-download) to verify that the readme field is not present in the manifest after publishing.
403 on S3 is often (always?) used instead of 404, maybe the rendered readmes of some crates were lost during some sort of a migration or update?
Maybe publishing an empty version bump (of your crate) with no real changes will fix this problem?

**Comment by SirWindfield** [comment] 2021-03-15 17:29
> thanks for looking into this. but according to the documentation that should not be needed. from the page which you linked:
> 
> > If no value is specified for this field, and a file named `README.md`, `README.txt` or `README` exists in the package root, then the name of that file will be used.

Could this be expanded to include lowercase filenames as well? I usually name them all lowercase and my files don't get shown on crates io.

**Comment by Turbo87** [comment] 2021-03-15 17:45
@SirWindfield you can explicitly specify a different filename if you prefer to use a different one. see https://doc.rust-lang.org/cargo/reference/manifest.html#the-readme-field for details.

**Comment by rursprung** [comment] 2021-03-29 10:12
for what it's worth: i published a new version of my lib (v0.4.0 and shortly thereafter also v0.4.1) and the README is now rendered correctly for them.

i'm not sure how you want to proceed with this ticket. i see multiple options:
* call it a random failure not worth investigating any further and close the ticket
* keep it open and use it to add better monitoring / diagnostics tooling for the README rendering on crates.io
* keep it open to track if others report the same problem but don't actively do anything on it
i'm fine with any. i would probably vote for the 2nd option, but to be honest, i don't know if anyway will want to invest time into this?

**Comment by Turbo87** [comment] 2021-03-29 10:18
thanks for the update. I guess we can close this issue for now and if it happens again we can try to investigate. :)

**Closed by Turbo87** 2021-03-29 10:18 UTC
