### ISSUE TITLE
Can't login on Android

### ISSUE THREAD

**Issue by naturallymitchell** [rust-lang/crates.io#1577] opened 2018-12-14 20:04 UTC
Sign in with GitHub doesn't seem to work.

**Comment by carols10cents** [comment] 2018-12-14 22:06
Which android version and which browser, please?

**Comment by mitchtbaum** [comment] 2018-12-14 22:48
Android 5, Chrome 70

**Comment by locks** [comment] 2019-09-07 18:52
Latest Chrome on Android is 76 and I cannot reproduce this issue, so I'm closing it for now.
If it's still an issue please let us know!

**Closed by locks** 2019-09-07 18:52 UTC
Labels: A-accounts
