### ISSUE TITLE
Wrong crate name of dependency in old Firefox.

### ISSUE THREAD

**Issue by vi** [rust-lang/crates.io#482] opened 2016-12-02 22:24 UTC
https://crates.io/crates/thrussh

> Dependencies
>
> * [thrussh](https://crates.io/crates/thrussh) ^0.0.10

While according to [Cargo.toml](https://docs.rs/crate/thrussh/0.6.0/source/Cargo.toml) it should be `libsodium-sys`.

Note: this is Firefox 38.0.6. In Firefox 45.2.0 and Chromium 53 it shows `libsodium-sys` like it should.

**Comment by ducks** [comment] 2017-01-30 18:35
It looks like thrussh dropped the libsodium-sys dep in 0.7.0 but crates.io shows the latest version by default which is 0.8.2.

https://docs.rs/crate/thrussh/0.7.0/source/Cargo.toml
https://crates.io/crates/thrussh/0.7.0

vs

https://docs.rs/crate/thrussh/0.8.2/source/Cargo.toml
https://crates.io/crates/thrussh

**Comment by carols10cents** [comment] 2017-02-11 03:01
So is there a bug here still...?

**Comment by vi** [comment] 2017-02-11 15:41
I've checked in Firefox 38.8.0 and it seems to be OK. [This page](https://crates.io/crates/thrussh/0.4.0) matches in FF 38.8 and FF 45.7.

**Comment by carols10cents** [comment] 2017-02-11 22:05
Ok, I'm going to close this then :)

**Comment by jpernst** [comment] 2017-03-29 22:06
I still notice this on FF 52.0.1, but it requires an addition step. On any crate page, click the FIRST dependency link to go to its page, then hit back to return to the original crate. The first dep will still have the correct version, but will be named as the crate itself rather than the actual dep. Doing so on any other dependency does not appear to trigger the bug, only the first one will cause it.

**Comment by carols10cents** [comment] 2017-03-29 22:28
@jpernst ooh!!! That is very helpful, thank you!!!!

**Comment by carols10cents** [comment] 2017-06-17 16:07
Ooops we already have an issue for that actually, closing this as a duplicate of #306 .

**Closed by carols10cents** 2017-06-17 16:07 UTC
Labels: A-ui, I-wrong, question
