### ISSUE TITLE
image-0.24.6 couldn't be used

### ISSUE THREAD

**Issue by Hell576** [rust-lang/crates.io#6598] opened 2023-06-12 14:36 UTC
### Current Behavior

cargo build
    Updating crates.io index
error: unable to get packages from source

Caused by:
  failed to parse manifest at `N:\Users\MAXUS\.cargo\registry\src\github.com-1ecc6299db9ec823\image-0.24.6\Cargo.toml`

Caused by:
  Features and dependencies cannot have the same name: `qoi`

### Expected Behavior

No problems with parsing manifest

### Steps To Reproduce

go to cargo.toml file 
write under [dependencies] row: "image="0.24.5" " or "image="0.24.6" "
write command "cargo run" (compiler ver 1.34) in project directory

### Environment

- Browser: Edge 114.0.1823.43
- OS: Win 10 22h2 LTSC

**Comment by Turbo87** [comment] 2023-06-12 14:50
Rust 1.34 is fairly outdated at this point. You might want to consider updating your compiler version to take advantage of these newer `image` releases.

Since this is not a bug in crates.io, but only an incompatibility of old Rust and newer `image` release I'll close this issue since there is not much we can do here.

**Closed by Turbo87** 2023-06-12 14:50 UTC
