### ISSUE TITLE
Crates.io does not show correct author info

### ISSUE THREAD

**Issue by achanda** [rust-lang/crates.io#179] opened 2015-08-06 21:53 UTC
*EDIT*
@azerupi has a better description of the issue below.

The author is always set to "The Rust Project Developers"

<img width="894" alt="screen shot 2015-08-06 at 2 52 30 pm" src="https://cloud.githubusercontent.com/assets/2165463/9124329/d4409e8e-3c4a-11e5-933d-be8ae13dea7d.png">

The `Cargo.toml` file for this repo does have correct author info.
```
:~/src/ipnetwork (master=)$ cat Cargo.toml
[package]
name = "ipnetwork"
version = "0.1.11"
authors = ["Abhishek Chanda <abhishe.becsk@gmail.com>"]
description = "A library to work with IP CIDRs in Rust, heavily WIP"
license = "Apache-2.0"
repository = "https://github.com/achanda/ipnetwork"

EDIT:
@azerupi pointed out that:
1. This bug appears only on crates that the current user owns.
2. The authors are listed as the authors of the last crate visited.
Please see screenshots below.

**Comment by azerupi** [comment] 2015-08-06 21:59
I was just about to report this bug, but it is not **always** set to "The Rust Project Developpers".

This bug appears only on crates you own and it shows as authors the authors of the last crate you visited.

![crates-bug02](https://cloud.githubusercontent.com/assets/7647338/9124441/1fc80cb0-3c97-11e5-859c-3cd08b5a34d7.png)
![crates-bug01](https://cloud.githubusercontent.com/assets/7647338/9124442/1fc99da0-3c97-11e5-9e22-14c9b6a27ddb.png)

**Comment by alexcrichton** [comment] 2015-08-11 00:28
I believe this is a dupe of https://github.com/rust-lang/crates.io/issues/70

**Closed by alexcrichton** 2015-08-11 00:28 UTC
