### ISSUE TITLE
error: failed to download from `https://crates.io/api/v1/crates/adler/1.0.2/download`

### ISSUE THREAD

**Issue by xMAC94x** [rust-lang/crates.io#3782] opened 2021-07-12 14:27 UTC
**Describe the bug**
during cargo clippy with the toolchain 2021-07-06 crates.io often reports that it failed to download some crate.
This rise up in our CI for multiple runners, multiple crates on different times per day. At first we thought its just a network issues, but there might be more to it. did you change any of the relevant setup ?

**To Reproduce**
sporadic issue, it fails when cargo tries to download various crates from crates.io. see here for logs

**Expected behavior**
The crate `adler` or similar downloads corectly and cargo continues to run

**Screenshots**
![image](https://user-images.githubusercontent.com/5282251/125304568-ffd33f80-e32d-11eb-8163-16a5a30a1fca.png)

**Server (please complete the following information):**
 - ubuntu20.04
 - cargo
 -  2021-07-06

**Comment by hi-rustin** [comment] 2021-07-12 14:35
Can this problem be reproduced in other network environments?

**Comment by insipx** [comment] 2021-07-13 19:12
had the same issue and came across this thread https://github.community/t/failed-sending-data-to-the-peer-connection-died-tried-5-times-before-giving-up/189130

pinning nightly to that version (2021-07-05) fixed the issue for me, although I don't know what actually causes the problem.

**Comment by JohnTitor** [comment] 2021-07-14 23:23
That seems to be a curl error, we actually bumped our curl dependency in https://github.com/rust-lang/rust/pull/86874 (it's used by Cargo). But it'd be quite hard to reproduce the failure and I'm not sure either 7.76.1 or 7.77.0 would cause it. Anyway, I think this is a cargo/curl issue rather than crate.io's, cc @rust-lang/cargo for awareness.

**Comment by alexcrichton** [comment] 2021-07-15 17:06
I tried to [dig in a bit](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/.22spurious.20network.20error.22) and opened an [upstream issue](https://github.com/curl/curl/issues/7400). In the meantime https://github.com/rust-lang/cargo/pull/9695 should help mitigate this issue since it will basically do more retries at a higher level (sweeping the bug under the rug)

**Comment by DaUs3103** [comment] 2021-07-19 20:45
Please help

**Comment by vakaras** [comment] 2021-07-20 17:23
> Please help

@DaUs3103  Have you tried to update to the latest nightly? At least it fixed the problem for me.

**Comment by JohnTitor** [comment] 2021-07-23 20:31
The cargo issue tracker now has https://github.com/rust-lang/cargo/issues/9697 and I'm going to close this in favor of it, thanks for reporting!

**Closed by JohnTitor** 2021-07-23 20:31 UTC
Labels: C-bug
