### ISSUE TITLE
Documentation link doesn't update when custom URL is removed

### ISSUE THREAD

**Issue by Ralith** [rust-lang/crates.io#1214] opened 2017-12-26 21:44 UTC
In the 0.5.1 release of [the openvr crate](https://crates.io/crates/openvr) I removed the custom documentation link from Cargo.toml as it was made redundant by docs.rs. Despite this, the obsolete link from previous releases is still being used, instead of being replaced with a docs.rs link as expected.

**Comment by starkat99** [comment] 2018-03-17 23:12
The same thing happened when I made the 0.3.0 release of [widestring](https://crates.io/crates/widestring). This means the documentation link for the crate is currently to a 404 error instead of using docs.rs. It would be nice if this could be fixed for existing crate releases as well, not just new crate publishes, so we don't have to make a new crate release just to fix this bug (assuming the bug gets fixed in first place).

**Comment by carols10cents** [comment] 2018-03-19 15:02
Sorry I didn't notice this before, but removing the documentation link is a duplicate of https://github.com/rust-lang/crates.io/issues/945 and a fix was deployed yesterday. 

We're not going to go back and fix old crates, but publishing a new version without a documentation link should fix it now.

**Closed by carols10cents** 2018-03-19 15:02 UTC
