### ISSUE TITLE
Unable to Login with GitHub

### ISSUE THREAD

**Issue by pranavarora1895** [rust-lang/crates.io#4575] opened 2022-02-17 07:57 UTC
### Current Behavior

I am not able to log in to crates.io via GitHub. The authorization window just pops up and disappears instantly.

### Expected Behavior

It should be addressed as it is causing a hindrance to many of the rustaceans. The authorization window that pops up should let the user click on the `authorize` button so that he/she can log in to the crates.io

### Steps To Reproduce

1. Go to [crates.io](https://crates.io/)
2. Click on `Log in with GitHub`.
3. You will see the bug.

### Environment

- Browser: Chrome
- OS: Win 10

### Anything else?

Please add other authentication options such as Google, Facebook, etc. so that there is ease to log in to crates.io

**Comment by Turbo87** [comment] 2022-02-17 08:03
I assume this is a duplicate of https://github.com/rust-lang/crates.io/issues/4176, but thanks for reporting

**Closed by Turbo87** 2022-02-17 08:03 UTC
Labels: C-bug

**Comment by pranavarora1895** [comment] 2022-02-17 09:14
You're Welcome. 😃

**Comment by pranavarora1895** [comment] 2022-02-20 03:36
When I was using the **Chrome Browser**, I was unable to log in. I was able to log in when I used **Brave Browser**. Hope it helps while debugging.
