### ISSUE TITLE
Issue with crate download counts starting Aug. 23

### ISSUE THREAD

**Issue by atouchet** [rust-lang/crates.io#7039] opened 2023-08-28 16:59 UTC
### Current Behavior

Starting Aug. 23 the download number for various crates appear to be unrealistically low. I suspect there is something wrong with the numbers being reported.

### Expected Behavior

I expected crate download numbers to be roughly in line with historical trends.

### Steps To Reproduce

1. Go to crates.io
2. Click on a page of a popular crate
3. See the low download count starting Aug. 23

### Environment

- Browser: Firefox 116.0.3
- OS: Windows 10

### Anything else?

Example behavior for the libc crate:

![Untitled-1](https://github.com/rust-lang/crates.io/assets/26315797/8899b4de-9da4-4b41-ac81-c1657ff5e706)

**Comment by Turbo87** [comment] 2023-08-29 07:30
thanks for reporting this. we've been aware that something is wrong since the weekend but we're still busy figuring out the root cause of this. we haven't been able to reproduce this locally or on our staging environment, which unforunately makes it hard to debug. figuring this out and fixing it is our first priority right now though! :)

**Comment by joshlf** [comment] 2023-08-29 07:52
In case it helps, I've observed that the effect is not uniform across all crates. Crates with more downloads seem to be more significantly affected. For example, compare [syn](https://crates.io/crates/syn) or [hashbrown](https://crates.io/crates/hashbrown) with [alsa](https://crates.io/crates/alsa) or [sys-locale](https://crates.io/crates/sys-locale).

**Comment by Turbo87** [comment] 2023-08-29 10:01
It looks like #7043 fixed it on our side. I'll report the issue to the dashmap devs and close it here :)

**Closed by Turbo87** 2023-08-29 10:01 UTC
Labels: C-bug 🐞, A-backend ⚙️
