### ISSUE TITLE
New design/layout is less user-friendly

### ISSUE THREAD

**Issue by d4h0** [rust-lang/crates.io#3352] opened 2021-02-28 18:42 UTC
**Is your feature request related to a problem? Please describe.**

It seems, there was a small redesign of the crate pages, which decrease the user-experience, in my opinion. I couldn't find an existing issue, so I'm creating this one.

Before there were links to the repo and the docs of a crate at the very top, now a visitor has to scroll down and search them in the right sidebar.

**Describe the solution you'd like**

Would it be possible to add these links back again? I'm probably not the only one who used that feature heavily.

Sometimes the crate.io page of a crate is the only page on Google (or at least at the top of the search results), and I often click this result, and then on the repo or docs link. With the new layout that workflow is significantly slower, because I first have to scroll down and find the links.

~There is a new "Readme" label now (I believe this wasn't there before, but I could be wrong), which is not very useful at all (as the Readme is directly below it).~  Actually, I just realized, that this is a tab. So this "label" is needed when other tabs are active.

To me, it also was more useful when the version history was in the sidebar (now there is an extra click).

**Describe alternatives you've considered**

I didn't consider anything else. I think the old layout was pretty good.

**Additional context**

Nothing, I could think of.

**Comment by icefoxen** [comment] 2021-03-02 20:26
Came here to make an issue just called "I love you, but please stop moving things that have been in the same place for years".  Seems to be more or less a duplicate of this one.

I don't really care where things are, as long as they stay there.  Muscle memory trumps everything.  Maybe we can move things in the layout once every Rust edition?

**Comment by d4h0** [comment] 2021-03-03 08:22
I agree. And I also think, often used things should be efficient to access (as they were before the redesign).

**Comment by mplsgrant** [comment] 2021-03-04 17:05
I came here suggest moving the list the crate's Dependencies section back to the right sidebar. I would regularly glance at the list of dependencies to get a quick feel for the bones of the crate.

**Comment by ijackson** [comment] 2021-03-08 00:59
It seems to me that the page would be better if the new keywords links were in the RH sidebar, and the nagivigation links to docs and repo went back to the top.

The set of keywords varies in size and the contents and ordering won't be stable.  So it will be quite rare for a user to want to quickly click on "the first keyword that comes up" and we don't want to encourage users to get into that habit.  One doesn't click on these without reading them at least in a minimal way.  Putting them in the RH sidebar would make more sense IMO.

(As an aside I wonder if the new keywords links feature was in any sense related to or partly prompted by or seen as an alternative way of addressing the use cases in #3185.)

**Comment by Anders429** [comment] 2021-03-20 18:54
I really agree with the issues brought up here. When I visit a crates.io page now, I have absolutely no clue where anything is. What makes it worse is that it changes every day. I'm fine with change, but the new layout doesn't seem to add anything, and actually hides important information (like dependencies, version history, etc.).

**Comment by Turbo87** [comment] 2021-12-23 01:36
while I appreciate the feedback, it sounds like most of it is just due to not being used to the new positions of things yet. we had good reasons for moving some of these things, mainly to enhance them with additional information, which wouldn't have been possible in their old positions due to space constraints.

**Closed by Turbo87** 2021-12-23 01:36 UTC
Labels: A-frontend
