### ISSUE TITLE
Support alternative storage (such as on-disk)

### ISSUE THREAD

**Issue by phrohdoh** [rust-lang/crates.io#734] opened 2017-05-20 13:12 UTC
I'd like to host a registry on my own hardware and not depend on AWS' S3 and instead pull from the filesystem of the host device from a known location (probably should be configurable in phase 2 of an implementation [or a symlink!]).

My naïve thoughts on this are to abstract the `s3` crate into a generic crate store interface and reimplement s3 to use that and add the new disk storage which would also implement the new interface.

This way, hopefully, more stores can be added as desired.

Is this something crates.io wants or should this be a separate project?

**Comment by carols10cents** [comment] 2017-05-20 14:00
So this is something I think crates.io's code should support, and in fact, it sort of already does, but not in a way that would be useful for your purposes ;)

[I recently did the abstraction you're describing](https://github.com/rust-lang/crates.io/pull/601) and I [added an `Uploader` enum](https://github.com/rust-lang/crates.io/pull/601/files#diff-0ac6e7175e6f1b6d1034a05ecef14320R14) that has variants for `S3` and `Local`. I mostly made the local uploader with development of crates.io in mind, to make it easier for people to set up a dev env they could publish to and download from without having to set up an S3 bucket.

The current problem with my approach is that I did the simplest thing that could possibly work: to allow download of the crate files, I [put them in the `dist` directory](https://github.com/rust-lang/crates.io/pull/601/files#diff-0ac6e7175e6f1b6d1034a05ecef14320R94) since files in that directory [are already being served directly by the `dist` middleware](https://github.com/rust-lang/crates.io/blob/99134626dca1c46609ee0815280eee0587ad0fa9/src/dist.rs) in order to serve the CSS/JS/images compiled by the frontend.

The problem is the dist directory gets blown away every time you rebuild the ember frontend, which is bad if you want your crates to be there later 😆

So I think what needs to be done to support what you want is:

  - Use a different location than `dist` for crates on disk
  - If using the local uploader, add middleware to serve the static files from that different location
  - Enable choosing the local uploader with environment variables in a nice way. This is where it gets a little tangled... we don't want this behavior to change:
    - If we're on heroku, where production crates.io is, and where this local uploading strategy won't work anyway since heroku doesn't allow you to use a persistent filesystem, we want to panic if the S3 env vars aren't set.
    - If we're developing crates.io, the local uploader should be the default, unless the `S3_BUCKET` environment variable is set.
    - If we're running a mirror that doesn't allow publishing, we can just point to crates.io's S3 bucket for downloading
    - Right now, [the `HEROKU` environment variable is what determines whether we're in production mode or not](https://github.com/rust-lang/crates.io/blob/99134626dca1c46609ee0815280eee0587ad0fa9/src/bin/server.rs#L49), and we still want that to be the case, but there should be a way to indicate production-mode-but-not-on-heroku as well

[Around here](https://github.com/rust-lang/crates.io/blob/99134626dca1c46609ee0815280eee0587ad0fa9/src/bin/server.rs#L56) is the logic to choose the uploader based on the prod/dev environment and whether we're a read-only mirror or not.

Let me know if you have any other questions!

**Comment by bIgBV** [comment] 2017-10-31 04:30
Hi @carols10cents I came across this issue after going through the impl period document and browsing the various issues tagged by `A-backend`. I'd like to work on this as my first contribution in rust for a few reasons:

* I already have experience building web applications in python and go, so this will be a great way to understand how the same works in rust
* I just finished going through the majority of the rust book and want to jump into the impl period  to help where I can
* You've laid out what needs to be done in an amazing manner. 
* This seems like a relatively okay(I don't want to say easy 😅 )  issue for a newbie to pick up.

Is there anything you'd like to mention before I get started setting the project up and digging in?

**Comment by carols10cents** [comment] 2017-10-31 13:39
Awesome, welcome @bIgBV!! One thing to mention is that my description is a bit outdated 😅 These two parts were done [as part of this PR](https://github.com/rust-lang/crates.io/pull/951) afaik:

> * Use a different location than dist for crates on disk
> * If using the local uploader, add middleware to serve the static files from that different location

Definitely check me though!

That PR does hardcode the `local_uploads` directory as the location for the crate files, @Phrohdoh is that sufficient for your needs or would you want to optionally customize that location through an environment variable?

The remaining bullet points about how the logic should work are still valid though. Please let me know if you have any questions or if stuff doesn't make sense as you dig in!

**Comment by bIgBV** [comment] 2017-11-11 04:24
So I was thinking about the design for the implementation for this story. Right now there are 2 types of `Replica`'s, what I propose is the following:

* Add another replica, I think `Secondary` would be a good idea. This means there are 3 kinds of replicas. 
  * `Primary` being the source of truth (crates.io).
  * `ReadOnly` (Not entirely sure what it is reading from right now)
  * and `Secondary` for all other types of replicas.
* Add a new environment variable (`SECONDARY_STORAGE` maybe?) to set up the replica type.

Using these two changes we can handle the production-but-not-on-heroku case as `HEROKU` will still be set but the storage can be set up separately.

Right now that would be `local_uploads` but we could introduce a new environment variable for configuring the local storage directory for the index.

Thought?

**Comment by Turbo87** [comment] 2021-03-11 10:44
we briefly discussed a related topic in our team meeting last week and concluded that this codebase is primarily intended to run the official crates.io registry itself. we do not officially support running the same codebase on your own hardware, except for development purposes.

since alternative storage options would likely increase the complexity of the codebase quite a bit we are unlikely to accept PRs in that direction due to the additional maintenance burden.

since there hasn't been a lot of movement on this issue in the past few years either I'm going to close this issue for now. we can always revisit this, should the situation change.

**Closed by Turbo87** 2021-03-11 10:44 UTC
Labels: A-backend, A-self-hosting, C-enhancement
