### ISSUE TITLE
Dependency link replaced by crate name on browser-back

### ISSUE THREAD

**Issue by jmagnuson** [rust-lang/crates.io#444] opened 2016-09-17 19:56 UTC
For some crates, when following a dependency link and then performing a browser-back to return to the original crate page, the previous link text is replaced by the name of the crate itself (e.g., [ahrs](https://crates.io/crates/ahrs) dependency `nalgebra` becomes `ahrs`; also occurs in multi-dependency lists such as [abc](https://crates.io/crates/abc)).

However, that doesn't appear to be the case for all crates (e.g., [nalgebra](https://crates.io/crates/nalgebra)), so maybe there's an issue with the metadata?

This has been tested on Chrome and Firefox, so I don't think it's a browser-specific issue.

**Comment by carols10cents** [comment] 2017-02-21 23:00
I think this is a dupe of #306, please reopen if I'm missing something :)

**Closed by carols10cents** 2017-02-21 23:00 UTC
Labels: A-ember, I-wrong
