### ISSUE TITLE
Login error covers login link

### ISSUE THREAD

**Issue by ehuss** [rust-lang/crates.io#3687] opened 2021-06-08 23:00 UTC
**Describe the bug**
When running `cargo login` to log in, it instructs you to visit https://crates.io/me.  Doing that, I see the following:

<img width="415" alt="image" src="https://user-images.githubusercontent.com/43198/121267716-78e40080-c871-11eb-837b-68b23092d828.png">

with no obvious clue what to do.  You have to wait for that error to go away to reveal the login link below it.  If you have a small-width display, the login link is further hidden behind a Menu drop-down.  Even then, it is not obvious what to do if you don't already know how crates.io authentication works.

**To Reproduce**
Be logged out.  Then visit https://crates.io/me.

**Expected behavior**
If you are not logged in, visiting https://crates.io/me should display a login page (or some sort of page to indicate you need to do something to proceed).  Another alternative is if you are already logged in to GitHub to automatically pass through, though I'm not sure how I feel about that. 

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Any

**Comment by wangkirin** [comment] 2021-06-09 06:26
I think this issue is caused by the adjustment of `header`  in PR #3681 
May be we need to adjust the position of notifications in sync.

**Comment by Turbo87** [comment] 2021-06-11 18:34
we've decided to revert the layout change for now until we've decided how we want to approach this issue

**Comment by ehuss** [comment] 2021-12-22 16:49
I think this was closed without being resolved (or maybe something changed in the meantime).  I still get the following behavior:

<img width="507" alt="image" src="https://user-images.githubusercontent.com/43198/147125717-3e5d41b4-84f9-4503-8ae9-111d02970ef8.png">

Covering the login link.

My expected behavior isn't about the positioning of the link or the error message.  It is that the entire page should be a clear message instructing the user how to log in (or, possibly skip that entire process if they have already authorized).  

That is, the current experience is:

1. Go to crates.io/me 
2. see home page with error message 
3. wait for error message to disappear 
4. determine that you need to click the sign in link
5. popup page to authorize with GitHub 
6. land in settings page.

I would expect it to be:

1. Go to crates.io/me 
2. page to authorize with GitHub 
3. land in settings page

**Comment by Turbo87** [comment] 2021-12-22 18:37
@ehuss yeah, I agree that I was too quick with resolving this. The primary issue reported here I think was caused by https://github.com/rust-lang/crates.io/pull/3681, which moved the login link to the far right side of the screen, which increase the chance of intersecting with that notification messages.

But I agree that the notification message itself it not a great solution, and I have a rough idea on how to implement a fullsize "you need to authenticate to visit this page" page.

**Closed** 2021-12-23 17:45 UTC
Labels: C-bug
