### ISSUE TITLE
https://crates.io/crates/getopt shows javascript error

### ISSUE THREAD

**Issue by HeapUnderfl0w** [rust-lang/crates.io#873] opened 2017-07-10 09:54 UTC
This may be related to issue #717 even though the console reports an 404 error.

When i browse to https://crates.io/crates/getopt i get the expected `Crate 'getopt' does not exist` error on the top of the page. Additionally i see an JavaScript error.

It appears on 3 different browser's (on the same machine) and on my mobile phone.
### Home Laptop
Microsoft Windows 10 Version 1703
#### Vivaldi (Chromium Fork)
Browser version: `1.10.867.38 (Stable channel) (32-bit)`
Image: https://i.imgur.com/bWJUMCY.png
Error Code: https://ghostbin.com/paste/yeub3

#### Firefox
Browser version: `54.0.1 (64-Bit)`
Image: https://i.imgur.com/Uq8pcOy.png
Error Code: https://ghostbin.com/paste/bd3ae

#### Edge
Browser Version: `Microsoft Edge 40.15063.0.0` & `Microsoft EdgeHTML 15.15063`
Image: https://i.imgur.com/kj0Qs0h.png
Error Code: https://ghostbin.com/paste/f2yah

### Mobile Phone
Samsung Galaxy S5  
LineageOS 14.1-20170705-NIGHTLY-klte
#### Chrome
Browser Version: `59.0.3071.125`
Image: https://i.imgur.com/4VCThAi.jpg
Error Code: https://ghostbin.com/paste/qrh8y
  
The correct page (https://crates.io/crates/getopts) loads without errors.

**Comment by carols10cents** [comment] 2017-07-10 14:27
Thanks for this report! This is a duplicate of #844 actually, I'm closing as such :)

**Closed by carols10cents** 2017-07-10 14:27 UTC
