### ISSUE TITLE
Docs build fails because of dns resolution

### ISSUE THREAD

**Issue by mdrokz** [rust-lang/crates.io#6002] opened 2023-01-26 09:34 UTC
### Current Behavior

Hi so im a maintainer of https://github.com/atroche/rust-headless-chrome and im having problem with docs build of the crate, the main culprit is [auto_generate_cdp](https://crates.io/crates/auto_generate_cdp/0.4.0) i use it as dependency in headless_chrome it fires an http request to 

https://raw.githubusercontent.com/ChromeDevTools/devtools-protocol/15f524c8f5ce5b317ddcdf5e6f875d6eb8bdac88/json/js_protocol.json and,

https://raw.githubusercontent.com/ChromeDevTools/devtools-protocol/15f524c8f5ce5b317ddcdf5e6f875d6eb8bdac88/json/browser_protocol.json

but the docs build log shows it failst to resolve `raw.githubusercontent.com` DNS 

refer to this https://docs.rs/crate/headless_chrome/1.0.1/builds/713766 and https://github.com/atroche/rust-headless-chrome/issues/355

### Expected Behavior

[auto_generate_cdp](https://crates.io/crates/auto_generate_cdp/0.4.0) should be able to resolve the DNS and the docs build should be successful

**Comment by Turbo87** [comment] 2023-01-26 09:40
this was caused by https://status.crates.io/incidents/dl21vcm8pt98. you might want to open an issue on the docs.rs repo so that the build can be restarted.

**Comment by mdrokz** [comment] 2023-01-27 10:37
> this was caused by https://status.crates.io/incidents/dl21vcm8pt98. you might want to open an issue on the docs.rs repo so that the build can be restarted.

Thanks for replying i created an issue here https://github.com/rust-lang/docs.rs/issues/2018

**Comment by Turbo87** [comment] 2023-01-27 10:39
great, I'll close this one then :)

**Closed by Turbo87** 2023-01-27 10:39 UTC
