### ISSUE TITLE
Crate index does not update immediately upon publishing a crate.

### ISSUE THREAD

**Issue by SiegeLord** [rust-lang/crates.io#1869] opened 2019-10-14 02:06 UTC
I have a project with a lot of interdependent crates. Recently, when I've tried to publish them all at once, I hit errors where the package index wasn't updated as soon as the package was published, causing the publishing of dependent packages to fail. This used to work fine, but now I get traces like this:

```
Publishing allegro_font-sys
    Updating crates.io index
   Packaging allegro_font-sys v0.0.36 (/home/siege/Projects/RustAllegro/allegro_font-sys)
   Verifying allegro_font-sys v0.0.36 (/home/siege/Projects/RustAllegro/allegro_font-sys)
   Compiling allegro-sys v0.0.36
   Compiling libc v0.1.12
   Compiling allegro_font-sys v0.0.36 (/home/siege/Projects/RustAllegro/allegro_font-sys/target/package/allegro_font-sys-0.0.36)
   Compiling allegro_util v0.0.36
    Finished dev [unoptimized + debuginfo] target(s) in 3.36s
   Uploading allegro_font-sys v0.0.36 (/home/siege/Projects/RustAllegro/allegro_font-sys)
Publishing allegro_ttf-sys
    Updating crates.io index
   Packaging allegro_ttf-sys v0.0.36 (/home/siege/Projects/RustAllegro/allegro_ttf-sys)
   Verifying allegro_ttf-sys v0.0.36 (/home/siege/Projects/RustAllegro/allegro_ttf-sys)
error: failed to verify package tarball

Caused by:
  failed to select a version for the requirement `allegro_font-sys = "= 0.0.36"`
  candidate versions found which didn't match: 0.0.35, 0.0.34, 0.0.33, ...
  location searched: crates.io index
required by package `allegro_ttf-sys v0.0.36 (/home/siege/Projects/RustAllegro/allegro_ttf-sys/target/package/allegro_ttf-sys-0.0.36)`
Traceback (most recent call last):
  File "./cargo_util.py", line 70, in <module>
    check_call(cargo_cmd('publish'), cwd=crate)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
```

Can anything be done to make this process more robust? For now I added a wait command between publish commands, but that seems hardly ideal.

**Comment by sgrif** [comment] 2019-10-15 19:57
The delay between `cargo publish` returning and the index being updated is expected behavior. You can find more information about the change in behavior, which occurred in March of 2019, [here](https://internals.rust-lang.org/t/changes-to-how-crates-io-handles-index-updates/9608).

> Can anything be done to make this process more robust?

This change was made to ensure that our web server isn't blocked by a potentially time consuming process, and to ensure index updates can be better retried when they fail. The delay is there to make this process more robust. If by "robust" you mean "cargo blocks until the index has been updated", I'd recommend opening an issue on Cargo. Any change to crates.io for this would ultimately undermine the original reason that this change was made in the first place.

> For now I added a wait command between publish commands, but that seems hardly ideal.

Publishing involves talking to a lot of different services over the network making many requests that can fail for reasons beyond the index not yet being updated. I'd recommend adding retry behavior (probably with a delay between retries for good measure), which would handle this case as well as make your publish script more robust.

Since there's nothing actionable on our side, I'm going to close this issue. But you should feel free to reply here if you have additional questions.

**Closed by sgrif** 2019-10-15 19:57 UTC
