### ISSUE TITLE
whole crate is marked as yanked if only last version is yanked

### ISSUE THREAD

**Issue by kstep** [rust-lang/crates.io#253] opened 2016-01-25 19:20 UTC
Steps to reproduce:

1. have several versions of a single package published (e.g. version 0.1.0, 0.1.1 and 0.1.2)
2. yank the last version with `cargo yank` (i.e. run `cargo yank --vers 0.1.2`)

Expected behavior:

Only version 0.1.2 is yanked, the crate's page on crates.io have all other versions accessible (0.1.0 and 0.1.1 in this example, 0.1.1 being the default and latest available version)

Actual behavior:

Whole crate is marked as yanked with a message on crate's page that the crate was removed from repository and only available for already published packages as a dependency.

**Comment by alexcrichton** [comment] 2016-01-25 19:25
I believe this is a dupe of https://github.com/rust-lang/crates.io/issues/76, but thanks for the report! If you let me know which crate was affected by this I can fix it up manually in the meantime.

**Closed by alexcrichton** 2016-01-25 19:25 UTC

**Comment by kstep** [comment] 2016-01-25 19:27
It was [mpd](https://crates.io/crates/mpd/), but I already republished it under another version, so it's OK now.
Thank you for pointing me to the existing issue. I searched for it, but I couldn't find it for some reason.
