### ISSUE TITLE
Crates.io should not require the `accept:` header to contain the string `html` 

### ISSUE THREAD

**Issue by AaronFriel** [rust-lang/crates.io#960] opened 2017-08-15 05:31 UTC
Microsoft Edge, `curl`, and likely other tools send `Accept: */*`. Crates.io is not accessible to these tools, and pages cannot be accessed via curl unless `Accept: text/html` or some variant containing html is sent.

https://github.com/rust-lang/crates.io/blob/d6eaeb8bd6d50fdac97d43dedb3747ae3169bf45/src/dist.rs#L42-L45

**Comment by kureuil** [comment] 2017-08-15 13:18
What version of Edge are you using ? I can browse the site just fine using *Microsoft Edge 40.15063.0.0* using *Windows 10 Pro 1703*.

What do you mean by "not accessible" ? Do you get an empty response ? a 404 ?
Does it looks like #788 ?

**Comment by AaronFriel** [comment] 2017-08-15 14:30
Yes, I get the 404 response because it did not send an Accept header that contains the string "html". I'm on the Insider Fast track on build 16257.

**Comment by AaronFriel** [comment] 2017-08-15 14:33
Update: It appears my Edge is now sending "Accept: text/html, application/xhtml+xml, image/jxr, */*", and all I've done since yesterday is restart. No clue why Edge was sending "Accept: */*". I'll file a ticket on that side, but the Crates.io server should consider "*/*" to include "html".

**Comment by carols10cents** [comment] 2017-08-17 02:15
This indeed sounds like a duplicate of #788.

**Closed by carols10cents** 2017-08-17 02:15 UTC
