### ISSUE TITLE
Non-null fields show up as null from API

### ISSUE THREAD

**Issue by moore3071** [rust-lang/crates.io#1267] opened 2018-02-22 22:49 UTC
@yatriks noted in #1026 that certain fields are showing up as null in the response from the API even though the field is not null. For an example we'll look at the reply from `https://crates.io/api/v1/crates?keyword=test&q=compiletest_rs` which is:

```json
{
  "crates": [
    {
      "id": "compiletest_rs",
      "name": "compiletest_rs",
      "updated_at": "2018-01-28T13:22:52.519949+00:00",
      "versions": null,
      "keywords": null,
      "categories": null,
      "badges": [],
      "created_at": "2015-05-09T09:20:56.585538+00:00",
      "downloads": 155752,
      "recent_downloads": 64315,
      "max_version": "0.3.6",
      "description": "The compiletest utility from the Rust compiler as a standalone testing harness",
      "homepage": null,
      "documentation": null,
      "repository": "https://github.com/laumann/compiletest-rs",
      "links": {
        "version_downloads": "/api/v1/crates/compiletest_rs/downloads",
        "versions": "/api/v1/crates/compiletest_rs/versions",
        "owners": "/api/v1/crates/compiletest_rs/owners",
        "owner_team": "/api/v1/crates/compiletest_rs/owner_team",
        "owner_user": "/api/v1/crates/compiletest_rs/owner_user",
        "reverse_dependencies": "/api/v1/crates/compiletest_rs/reverse_dependencies"
      },
      "exact_match": true
    }
  ],
  "meta": {
    "total": 1
  }
}
```

Meanwhile if we look at the page for [compiletest_rs](https://crates.io/crates/compiletest_rs) we can see that the following fields shouldn't have been returned as null:
- versions
- keywords
- documentation

**Comment by yatriks** [comment] 2018-02-23 01:29
Hey @moore3071, dug around about this a bit more.

There are two relevant API endpoints here, the search endpoint (`/crates?q=*`) and the show endpoint (`/crates/:crate_id`). Going to refer to them as that, but let me know if there are more canonical ways to refer to them.

There are two separate problems I think:

**1.** The following three keys affected only in the search API but _not_ in the show API are:
- `versions`
- `keywords`
- `categories`

**2.** The `documentation` key does indeed appear to be null for both in the case of `compiletest_rs`, but not other crates (e.g. `filetime` has documentation present in both the [search](https://crates.io/api/v1/crates?q=filetime&keyword=timestamp) and the [show](https://crates.io/api/v1/crates/filetime) APIs).

**For problem 1.**,
I think this comes down to the difference between `krate.encodable` (which is what the show endpoint uses) and `krate.minimal_encodable` (which is what search endpoint uses). In the definition of `minimal_encodable`, those 3 keys are manually set to `None`:
```
pub fn minimal_encodable(
    self,
    max_version: &semver::Version,
    badges: Option<Vec<Badge>>,
    exact_match: bool,
    recent_downloads: Option<i64>,
    ) -> EncodableCrate {
  self.encodable(
      max_version,
      None, // versions
      None, // keywords
      None, // categories
      badges,
      exact_match,
      recent_downloads,
    )
}

```
The `/summary` endpoint [also uses `minimal_encodable`](https://github.com/rust-lang/crates.io/blob/master/src/controllers/krate/metadata.rs#L38), and you can see [its response is the same](https://crates.io/api/v1/summary) as the search endpoint.
If we do want to return these fields in the search API, we can add the tests for the values of each of those keys (as done in [the tests for the show endpoint](https://github.com/rust-lang/crates.io/blob/master/src/tests/krate.rs#L399)) to the tests for the search endpoint. It should be a straightforward task to change `minimal_encodable` to `encodable` in the search endpoint.
Alternatively, this is by design, and should just be documented (arguably these fields aren't always necessary for a search result endpoint, but unsure if there are things relying on them).

**For problem 2.**
`documentation` shows up in the frontend when the API returns `null` because it appears that `fetchCrateDocumentation` pings https://docs.rs async in case there is auto-generated documentation for that. 
That value is never in the database, which is why I assume the API doesn't return it.

**Comment by moore3071** [comment] 2018-02-23 04:47
Wow, that was some good digging @yatriks! It appears from what you posted that it's functioning as designed.

The easiest solution to avoid future issues would be to document it, but I personally think this is poor design and should be changed instead. An API shouldn't return a field with an incorrect value. I can think of two solutions:

1. As @yatriks mentioned the `minimal_encodable` field could be changed to `encodable` in the search endpoint. I'd imagine that the reason this option wasn't chosen by default is to avoid making a large number of unnecessary queries to the database. As such, this is probably an undesirable solution.

2. Omit the always-null fields from the search endpoint's JSON response. The easiest way to do this from a brief look at the code would be providing an additional view, such as `MinimalEncodableCrate` which would omit these always-null fields.

**Comment by sgrif** [comment] 2018-05-03 21:48
I'm going to close this issue, as it's definitely functioning as designed. We definitely want to provide proper API documentation at some point in the future. In the mean time, I'd accept a PR that omits the always null fields from the response entirely (I suspect there's a serde config to do this that doesn't require introducing an entirely new struct)

**Closed by sgrif** 2018-05-03 21:48 UTC
