### ISSUE TITLE
Investigate index self-healing

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/crates.io#2230] opened 2020-02-26 12:42 UTC
The crates.io data is split between the PostgreSQL database (hosted on Heroku) and the git index (hosted on GitHub). Those two databases got out of sync in the past, and that might happen again due to bugs in the crates.io application.

We should investigate whether we want to implement a self-healing periodic background job, which checks the consistency of the data and tries to repair it automatically, and whether it's feasible to implement it.

**Comment by pietroalbini** [comment] 2020-02-26 12:44
I personally think this is not something we should do: desyncs happen rarely, and if they happen it means there is a bug in the crates.io application (otherwise the failed job would be re-queued, and if it stays in the queue too long someone gets paged). I'd prefer for us to investigate the causes of those desyncs manually instead of relying on another job to eventually apply a band-aid.

cc @smarnach @jtgeibel

**Comment by jtgeibel** [comment] 2020-03-05 01:19
> I personally think this is not something we should do

I agree.  In this case in particular, self-healing would be extra difficult because the bug was in code that would itself be used by any logic trying to fix the index.

I'd much rather have monitoring in place that would alert us if any desyncs are detected so that we can manually investigate and resolve any issues.  (Even if we had an automated recovery we would still want to be alerted to resolve the root cause, so I don't think automated recovery buys us a whole lot here anyway.)

**Comment by jtgeibel** [comment] 2020-04-16 01:57
I'm closing this because I don't think there is more for us to investigate at this time.  At a minimum, we need the ability to first detect the discrepancy as described in #2227 and I think that is the key improvement here.  If there are ideas for how to implement self-healing, anyone should feel free to provide suggestions here and we can discuss/reopen.

**Closed by jtgeibel** 2020-04-16 01:57 UTC
