### ISSUE TITLE
[search] Allow sorting by Most Recently Updated

### ISSUE THREAD

**Issue by behnam** [rust-lang/crates.io#1253] opened 2018-02-10 01:13 UTC
The current three options are:
1. Relevance
2. All-Time Downloads
3. Recent Downloads

<img width="176" alt="screen shot 2018-02-09 at 5 11 50 pm" src="https://user-images.githubusercontent.com/37169/36056799-663e3338-0dbc-11e8-8548-bd5e22270f72.png">

It would be great to have more options here, specially parameters around package updates, like  Most Recently Updated.

**Comment by moore3071** [comment] 2018-02-12 23:12
This seems like it might be a duplicate of #1210.

**Comment by carols10cents** [comment] 2018-02-14 13:50
Yep! Closing as duplicate of #1210.

**Closed by carols10cents** 2018-02-14 13:50 UTC
