### ISSUE TITLE
Searching for stm32f103 does not find stm32f103xx crate

### ISSUE THREAD

**Issue by nagisa** [rust-lang/crates.io#884] opened 2017-07-13 16:07 UTC
What the title says.

Searching for stm32 does find it though (2nd page).

**Comment by sgrif** [comment] 2017-07-13 20:41
Seems like full text search doesn't match this, since there's no common root between them (as they aren't real words). Should be easy to fix, we should probably just add an `OR name LIKE '%search%'` onto the query.

**Comment by carols10cents** [comment] 2017-08-02 15:44
Oooh actually this is a duplicate of #700! Closing in favor of that one :)

**Closed by carols10cents** 2017-08-02 15:44 UTC
Labels: A-backend, A-search, C-bug, E-easy, E-mentor, P-low
