### ISSUE TITLE
"No dependent crates" is being shown while information is being loaded.

### ISSUE THREAD

**Issue by vi** [rust-lang/crates.io#1154] opened 2017-10-30 22:09 UTC
Steps to reproduce:

1\. Go to https://crates.io/crates/nix
2\. See "Loading..."

Expected:

3\. See something like "Loading dependent crates..." (if it is really needed. Ideally the number of dependent crates should come from the beginning.).
4\. See the "Dependent crates" link, or even better "Dependent crates(137)".

Actual:

3\. See "No dependent crates".
4\. After about half a second, see "Dependent crates" link.

**Comment by carols10cents** [comment] 2017-10-30 23:32
This is a duplicate of #554, right?

**Closed by carols10cents** 2017-10-30 23:32 UTC
