### ISSUE TITLE
Not able to see a crate that I own in "My Crates"

### ISSUE THREAD

**Issue by devashishdxt** [rust-lang/crates.io#2745] opened 2020-09-02 02:01 UTC
I'm the author of [`connect`](https://crates.io/crates/connect). But, when I go to [My Crates](https://crates.io/me/crates), I don't see it. How can I get its ownership back?

**Comment by jtgeibel** [comment] 2020-09-29 21:26
@devashishdxt sorry for the delay in resolving this. For anyone reading this with a similar issue, it's usually better to email us at help@crates.io for these sorts of problems.

This usually happens when a user deletes their GitHub account and creates a new one. We track ownership by GH user id, because usernames on GH can be reclaimed by anyone.

I've confirmed that you have verified the same email address for both accounts on crates.io, so I've transferred ownership of `connect` from your old account over to your active account.

**Closed by jtgeibel** 2020-09-29 21:26 UTC
