### ISSUE TITLE
Can not search the `which` crate in crates.io

### ISSUE THREAD

**Issue by fangyuanziti** [rust-lang/crates.io#774] opened 2017-06-14 02:53 UTC
I published a crate named `which` is crates.io. Howerver I can not find it by search `which` keyword in the website. Can you guys give me some suggestion to fix it?

The `which` crates address:
https://crates.io/crates/which

**Comment by carols10cents** [comment] 2017-06-14 12:44
Closing as a duplicate of #321. Sorry about that, we'll work on fixing it soon!

**Closed by carols10cents** 2017-06-14 12:44 UTC
