### ISSUE TITLE
searching for substring "rustc-ap" of crate name yields 0 results

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/crates.io#1573] opened 2018-12-07 12:02 UTC
I was searching for "rustc-ap.*" crates on the website, when searching for "rustc-ap", 0 results are shown which is strange because it is literally a substring of the crate name.
https://crates.io/search?q=rustc-ap

Searching for "rustc-" or "rustc" does find some of them though, I wonder what is going on here..
https://crates.io/search?q=rustc-
https://crates.io/search?q=rustc

**Comment by therealprof** [comment] 2019-02-14 19:27
Yeah, we have the same problem with other crates as well, like [`stm32f1`](https://crates.io/search?q=stm32f1) doesn't find `stf32f1xx-hal`.

CC @sgrif We talked about this at the RaH and you mentioned a potential fix?

**Comment by jeramyRR** [comment] 2019-03-10 01:23
I guess I'm not the first to discover the search issue since there's a ticket on it already.  I tried searching for soap and get a few libs back, but soapysdr wasn't listed even though it exists.

**Comment by kzys** [comment] 2019-04-16 06:46
@sgrif @FreeMasen Wouldn't be covered by https://github.com/rust-lang/crates.io/pull/1560?

**Comment by FreeMasen** [comment] 2019-04-18 19:04
@kzys I believe this would be fixed if #1560 is merged

**Comment by carols10cents** [comment] 2019-04-23 23:44
Yes, I think this is a duplicate of #159 and will be addressed by #1560. I'm taking a look at #1560 now!

**Closed by carols10cents** 2019-04-23 23:44 UTC
