### ISSUE TITLE
Have Oct 26 downloads stats disappeared ?

### ISSUE THREAD

**Issue by a1phyr** [rust-lang/crates.io#3093] opened 2020-12-15 00:53 UTC
**Describe the bug**
Download stats of Oct 26 seem to be gone.

It isn't really important, but I'm nonetheless interested in what happened.

I opened the same page on crates.io with a few hours of difference today, and in the second one Oct 26's stats were gone:

First one (missing day highlighted)
![image](https://user-images.githubusercontent.com/47725341/102153096-b6de0a00-3e76-11eb-81e5-8bfe53a75596.png)

Second one (note the missing download spike)
![image](https://user-images.githubusercontent.com/47725341/102153155-dffe9a80-3e76-11eb-96a6-1cac9c524eaf.png)

Interestingly, the graph are identical before Oct 26, but shifted of one day after.

Calling the API directly gives the same result as the second image (the last one).

Without having an old page, the issue can be observed in a highly downloaded crate, for example [syn](https://crates.io/crates/syn). In these crates, there are usually less downloads during the weekend, and this can easily be spotted. Except on Oct 25-26, where the weekend seems to last a single day...
![image](https://user-images.githubusercontent.com/47725341/102153755-37e9d100-3e78-11eb-934c-53883e42582e.png)

So, where is Oct 26 gone ?

**Comment by a1phyr** [comment] 2020-12-15 01:10
It has come back to normal at around 1am UTC (2am local time) :thinking:

**Comment by Turbo87** [comment] 2021-02-14 12:27
this may have been a display issue or related to the 7-day average calculation, but I can't reproduce it anymore since moving to the Chart.js implementation. if this happens again please reopen this issue 🙏

**Closed by Turbo87** 2021-02-14 12:27 UTC
Labels: C-bug
