### ISSUE TITLE
"403 Forbidden" when downloading some crates

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/crates.io#1200] opened 2017-12-07 09:51 UTC
Playing around with https://github.com/est31/cargo-local-serve (CC @est31) I noticed that the `download-all-crates` program produces fewer files than it said it was looking for. Here is the filtered output of running it again:

```rust
% cargo run --release --bin download-all-crates|grep -v verified
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/download-all-crates`
Loading all crates json...
The target is 71928 files.
Using directory /home/simon/projects/cargo-local-serve/crate-archives to store the files.
[10502/71928] Downloading cargo-ctags v0.2.3
Got error from server: 403 Forbidden
[24435/71928] Downloading glib-2-0-sys v0.0.1
Got error from server: 403 Forbidden
[24436/71928] Downloading glib-2-0-sys v0.0.2
Got error from server: 403 Forbidden
[24437/71928] Downloading glib-2-0-sys v0.0.3
Got error from server: 403 Forbidden
[24438/71928] Downloading glib-2-0-sys v0.0.4
Got error from server: 403 Forbidden
[24439/71928] Downloading glib-2-0-sys v0.0.5
Got error from server: 403 Forbidden
[24440/71928] Downloading glib-2-0-sys v0.0.6
Got error from server: 403 Forbidden
[24441/71928] Downloading glib-2-0-sys v0.0.7
Got error from server: 403 Forbidden
[24442/71928] Downloading glib-2-0-sys v0.0.8
Got error from server: 403 Forbidden
[24443/71928] Downloading glib-2-0-sys v0.1.0
Got error from server: 403 Forbidden
[24444/71928] Downloading glib-2-0-sys v0.1.1
Got error from server: 403 Forbidden
[24445/71928] Downloading glib-2-0-sys v0.1.2
Got error from server: 403 Forbidden
[24446/71928] Downloading glib-2-0-sys v0.2.0
Got error from server: 403 Forbidden
[25114/71928] Downloading gobject-2-0-sys v0.0.2
Got error from server: 403 Forbidden
[25115/71928] Downloading gobject-2-0-sys v0.0.3
Got error from server: 403 Forbidden
[25116/71928] Downloading gobject-2-0-sys v0.0.4
Got error from server: 403 Forbidden
[25117/71928] Downloading gobject-2-0-sys v0.0.5
Got error from server: 403 Forbidden
[25118/71928] Downloading gobject-2-0-sys v0.0.6
Got error from server: 403 Forbidden
[25119/71928] Downloading gobject-2-0-sys v0.0.7
Got error from server: 403 Forbidden
[25120/71928] Downloading gobject-2-0-sys v0.0.8
Got error from server: 403 Forbidden
[25121/71928] Downloading gobject-2-0-sys v0.0.9
Got error from server: 403 Forbidden
[25122/71928] Downloading gobject-2-0-sys v0.1.0
Got error from server: 403 Forbidden
[25123/71928] Downloading gobject-2-0-sys v0.2.0
Got error from server: 403 Forbidden
[70804/71928] Checksum mismatch for wright v0.2.2. Deleting. expected: '8261a34961de4a333d2c8e15309c32d35df864709799112002edcffc1316369f' was: '14f813076f3bd61b143e7094808057970f40366ee27b1252b758b407fbc661d2'
[70804/71928] Downloading wright v0.2.2
```

Indeed, requesting https://d19xqa3lc3clo8.cloudfront.net/crates/cargo-ctags/cargo-ctags-0.2.3.crate or https://s3.amazonaws.com/crates-io/crates/cargo-ctags/cargo-ctags-0.2.3.crate returns a 403 error.

Is this a bug, or are some files deliberately made not-public-readable?

**Comment by est31** [comment] 2017-12-07 10:07
Dupe of #1177 .

**Comment by SimonSapin** [comment] 2017-12-07 10:21
Oops, sorry.

**Closed** 2017-12-07 10:29 UTC
