### ISSUE TITLE
UX issue: error message masks the login button

### ISSUE THREAD

**Issue by lovasoa** [rust-lang/crates.io#3688] opened 2021-06-09 08:49 UTC
**Describe the bug**

The "please login to proceed" error message is displayed... on top of the button that would allow logging in. 

**To Reproduce**
1. Log out of crates.io
1. Go to 'https://crates.io/me'
4. The error message asking to log in covers the login button

**Expected behavior**

Instead of an error message, the page could just display "please log in to proceed" with a login form.

**Screenshots**

![image](https://user-images.githubusercontent.com/552629/121322987-bac38400-c90f-11eb-8161-be24a71614e0.png)

**Comment by Turbo87** [comment] 2021-06-09 10:02
duplicate of #3687

**Closed by Turbo87** 2021-06-09 10:02 UTC
Labels: C-bug
