### ISSUE TITLE
Highlight "perfect match" in search

### ISSUE THREAD

**Issue by killercup** [rust-lang/crates.io#649] opened 2017-03-25 18:13 UTC
I was just looking at <https://crates.io/search?q=mail&sort=downloads> and wondered why the "mail" crate with 33 downloads is on top of the list I specifically sorted by download count. Long code dive short, it's because it's a "perfect match" for my query and gets [special treatment](https://github.com/rust-lang/crates.io/blob/46d40902b4b5cc87eb223fcab44b38c540e41557/src/krate.rs#L679).

That's fine and all, but I think these entries should be highlighted a bit to justify their position. Especially when, as in the "mail" case, the perfect match is a placeholder crate.

**Comment by carols10cents** [comment] 2017-03-25 18:25
This is a duplicate of #493. Thanks!

**Closed by carols10cents** 2017-03-25 18:25 UTC
