### ISSUE TITLE
Rendered intra-project README links are broken

### ISSUE THREAD

**Issue by alilleybrinker** [rust-lang/crates.io#974] opened 2017-08-19 18:39 UTC
This issue can be seen here, with the "`examples/`" link: https://crates.io/crates/finchers

Basically, GitHub allows links to folders and files within the repo, and those links don't work on crates.io. This seems pointy, although I am not sure how best to resolve it.

**Comment by joshtriplett** [comment] 2017-08-19 20:38
As a first pass, transforming relative URLs to URLs relative to the repository might make sense.

**Comment by kivikakk** [comment] 2017-10-16 08:32
This is tricky; it won't work well in 100% of cases because a repository URL might be something like <<https://github.com/kivikakk/blah>>, but the URL to a file in that repository is like <<https://github.com/kivikakk/blah/blob/master/file.md>>.

We can assume that the main branch is `master` and so just always prepend `{repository}/blob/master/` and we'll get the 95% case fixed, which is way better than the current situation (a bunch of broken links).

**Comment by kivikakk** [comment] 2017-10-16 09:21
A proposal implementing the above is at https://github.com/rust-lang/crates.io/pull/1131. There's an ammonia-related caveat I'll see if I can get support from upstream for a fix.

**Comment by kivikakk** [comment] 2017-10-30 22:43
This should now be fixed; the example at <<https://crates.io/crates/finchers>> will be once we rerender READMEs.

**Comment by benoittgt** [comment] 2018-01-25 08:12
I have a weird behavior on https://crates.io/crates/git-changelog
Links in the [original readme](https://github.com/aldrin/git-changelog) are written like this:
```markdown
A commit [like this](src/assets/sample-commit.message)
```
github converts them as 
```html
<p>A commit <a href="/aldrin/git-changelog/blob/master/src/assets/sample-commit.message">like this</a>
this</a>.</p>
```

creates.io generates
```
<a href="https://github.com/aldrin/git-changelog/blob/master/resources/sample-commit.message" rel="nofollow noopener noreferrer">like this</a>
```

**Comment by carols10cents** [comment] 2018-01-25 17:40
Hi @benoittgt, could you open a new issue please?

**Comment by carols10cents** [comment] 2018-01-25 17:41
Actually nevermind, I saw the comment saying "this should be fixed" and thought this issue was closed. This is fine!

**Comment by kivikakk** [comment] 2018-01-26 00:35
I'll have a look into this shortly!

**Comment by kivikakk** [comment] 2018-01-26 03:47
I've tested locally that the following test passes:

```rust
    #[test]
    fn relative_link_test() {
        assert_eq!(
            markdown_to_html("A commit [like this](src/assets/sample-commit.message) generates an output [like this](src/assets/sample.md).", Some(&"https://github.com/aldrin/git-changelog")).unwrap(),
            "<p>A commit <a href=\"https://github.com/aldrin/git-changelog/blob/master/src/assets/sample-commit.message\" rel=\"nofollow noopener noreferrer\">like this</a> generates an output <a href=\"https://github.com/aldrin/git-changelog/blob/master/src/assets/sample.md\" rel=\"nofollow noopener noreferrer\">like this</a>.</p>\n");
    }
```

So where on earth is the substring replacement of `srt/assets` to `resources` happening? The [uploaded README](https://d19xqa3lc3clo8.cloudfront.net/readmes/git-changelog/git-changelog-0.2.1.html) has the replacements already made.

**Comment by kivikakk** [comment] 2018-01-26 03:56
I've published the crate to a locally-running server and have confirmed everything is working OK — the generated README has the correct links. Is there something about crates.io's production setup that could be causing this substitution? Maybe something with CloudFront?

![screen shot 2018-01-26 at 14 55 10](https://user-images.githubusercontent.com/1915/35424643-fe427532-02a8-11e8-9400-1db38420d5bd.png)

**Comment by kivikakk** [comment] 2018-01-26 03:59
Oh, hold the phone, I'm mistaken. It _is_ a link to `resources/…` in 0.2.1: https://github.com/aldrin/git-changelog/blame/v0.2.1/README.md#L9-L10

There hasn't been a release since it was changed to `src/assets` in https://github.com/aldrin/git-changelog/commit/76dbed62a40980d47f84b9ca82e1b72b391e7af0. 😅

**Comment by Turbo87** [comment] 2021-03-21 10:19
it sounds like this issue is resolved now, so I'll close it now. let me know if that assumption is wrong 😉

**Closed by Turbo87** 2021-03-21 10:19 UTC
Labels: A-readme, C-bug
