### ISSUE TITLE
Crate name / search term should be in the page title

### ISSUE THREAD

**Issue by upsuper** [rust-lang/crates.io#1930] opened 2019-11-28 12:41 UTC
When I'm looking for some crates, I end up getting several crates.io pages which basically look the same from the title, which is unfortunate.

![crates-io-screenshot](https://user-images.githubusercontent.com/333750/69807020-59a9f300-1238-11ea-809b-5178e966dc9a.png)

I suggest that the page title should include the crate name / search term etc., and ideally at the beginning of the page title, which would make it easier to find the desired page.

**Comment by smarnach** [comment] 2019-11-28 16:03
I agree with this suggestion. I think a title in the form "<search term> · Search results · crates.io" or "<crate name> · crates.io" would make sense. This is in line with what Wikipedia and many other web pages do.

**Comment by hbina** [comment] 2019-11-30 18:55
Any related files that I can look at?

**Comment by phlopsi** [comment] 2019-12-01 13:45
Someone changed the title generation over the course of the last two (?) months. Previously, when I bookmarked a crate page it'd always show, e.g. "serde - Cargo: packages for Rust", "lalrpop - Cargo: packages for Rust", etc. The current title being the same for every crate ("crates.io: Rust Package Registry") is a clear feature regression. It's annoying, that I have to edit every bookmark to contain the crate name, now. Rather than an enhancement, this should be treated as a bug, because we already had this feature and someone removed it.

If this feature gets re-implemented I'd suggest, that a should be test added, that checks, if the crate name is somewhere inside the page title. Clearly, if someone removes a test, it must be noticed and questioned during code review, i.e. a test should prevent any future PRs to remove this feature, **again**.

**Comment by smarnach** [comment] 2019-12-01 21:33
@phlopsi There has been a change to the branding in #1787, but this really only changed the strings from "Cargo" to "crates.io". But it is true that this used to work correctly, and we even have a [test for it that still passes](https://github.com/rust-lang/crates.io/blob/4a1542cb17ae50c2bfd0f7e85876d82617e30415/tests/acceptance/crate-test.js#L70). Clearly something has regressed, so I will tag this as a bug instead.

**Comment by carols10cents** [comment] 2019-12-02 19:07
Interesting, so I think the tests are passing because of [this commit](https://github.com/rust-lang/crates.io/commit/034fd451e3c66ea09217600629c5ff45c4e86ade), which was trying to work around [Testem](https://www.npmjs.com/package/testem) adding its own title element. The [testem team feels that testing the title should be done at an integration test level](https://github.com/testem/testem/issues/195).

There are indeed 2 `<title>` elements on pages like https://crates.io/search?q=test, which I can see by doing `document.head.getElementsByTagName('title')` in the developer console.

[This PR](https://github.com/rust-lang/crates.io/pull/1342) added a generic `<title>` to fix [an issue with ember-page-title that caused NO titles to appear](https://github.com/rust-lang/crates.io/issues/1341), and [the tests for the titles didn't fail then either :(](https://github.com/rust-lang/crates.io/issues/1341#issuecomment-381048314)

So I wonder if we need to update [ember-page-title](https://www.npmjs.com/package/ember-page-title)? We're currently on 4.0.5 and the latest is 5.1.0.

There's also this interesting note in the README:

> Non-fastboot apps should keep the <title> tag in index.html to ensure that the initial page is valid HTML. The title will be removed and replaced when your app boots.
> 
> Fastboot apps MUST remove the <title> tag from index.html.

We're, uh, [both](https://github.com/rust-lang/crates.io/pull/1900). So I'm not sure what we need to do here, but it seems like we're doing the wrong thing.

**Comment by carols10cents** [comment] 2020-01-02 19:32
Fixed by #2074, I'm working on deploying this soon.

**Closed by carols10cents** 2020-01-02 19:32 UTC
Labels: A-ui, C-bug, E-help-wanted, E-medium, P-medium
