### ISSUE TITLE
403 forbidden on README.

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/crates.io#968] opened 2017-08-19 17:15 UTC
[`tokei`](https://crates.io/crates/tokei)'s README is getting a 403 forbidden.

**Comment by carols10cents** [comment] 2017-08-27 01:54
So because you have [an `include` key in tokei's Cargo.toml](https://github.com/Aaronepower/tokei/blob/master/Cargo.toml#L6-L14) and the value for `include` does not list README.md, the README isn't actually in the `.crate` archives. Do you not want your README in the .crate files purposefully?

I see that tokei's readme DOES show up on https://crates.io/crates/tokei now, because you've since published 6.1.0. `cargo publish` sends the readme separately from the `.crate` archive, and saves the latest received readme content in the database for use during searching. The readme rendering that happens on publishing is also using that.

However, we have a script that rerenders readmes that isn't looking in the database at all. So for example, tokei 6.1.0's readme has a table, and we changed markdown renderers to fix that, but the script to RErender readmes is only looking in the `.crate` archives for readmes, so it wasn't able to rerender tokei's and the old html wasn't replaced. That's definitely an enhancement we should make for the most recent version, at least. I filed #1019 for that.

To support crates that have a readme, a repository URL, and don't have the readme in the `.crate` archive, I suppose we could fall back further to request it from the repository?

**Comment by Aaronepower** [comment] 2017-08-27 02:10
@carols10cents I excluded the README since I had to add the include at one point as I was hitting the 10MB limit for a crate on [https://crates.io](crates.io), and since I don't think anyone can actually request the crate's source I didn't think it needed to be included.

**Comment by Turbo87** [comment] 2020-10-13 01:29
it looks like the root cause was identified here and since there wasn't much activity lately I'll go ahead and close this issue now

**Closed by Turbo87** 2020-10-13 01:29 UTC
Labels: A-readme, C-bug
