### ISSUE TITLE
Changing href text when going back on Firefox

### ISSUE THREAD

**Issue by z1mvader** [rust-lang/crates.io#686] opened 2017-04-23 20:18 UTC
Hey guys. 

I'm having a little bug. When I enter into a crate page. For example:

https://crates.io/crates/sprs

And i select one of its dependencies (ndarray ^0.7.1) it takes me to the correct page. But when i go back one page into the Firefox history (pressing the top-left arrow on the navigation bar or pressing Alt-Left) the text of the dependency href now says: sprs ^0.7.1 (which is the name of the crate)

**Comment by carols10cents** [comment] 2017-04-23 22:04
Thanks for the report! This is a duplicate of https://github.com/rust-lang/crates.io/issues/482, though, so I'm closing in favor of that one.

Also please keep in mind that not everyone on the internet is a guy! Thanks!

**Closed by carols10cents** 2017-04-23 22:04 UTC

**Comment by z1mvader** [comment] 2017-04-23 22:13
Thanks for your fast answer! Sorry about the "guys" thing, I'll take into acount for my next issue :)
