### ISSUE TITLE
linux_l6470 0.1.1 available in the index but not on crates.io

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/crates.io#1458] opened 2018-07-10 16:45 UTC
While triaging Crater errors I noticed the version `0.1.1` of the [linux_l6470](https://crates.io/crates/linux_l6470) crate is [available in the index](https://github.com/rust-lang/crates.io-index/blob/ddeb51c4821641d92a1ea3272143e6719de38d0e/li/nu/linux_l6470) but [not on crates.io](https://crates.io/crates/linux_l6470/0.1.1). That means both [Crater](https://cargobomb-reports.s3.amazonaws.com/pr-51952-2/974ece59a1c76f424fe80f13996a4acd44e0ccf7-alt/reg/linux_l6470-0.1.1/log.txt) and Cargo can't download the latest version of the crate:

```
pietro@january: ~/tmp/foo (master)$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading linux_l6470 v0.1.1                                                 
error: unable to get packages from source                                       

Caused by:
  failed to get 200 response from `https://crates.io/api/v1/crates/linux_l6470/0.1.1/download`, got 404
pietro@january: ~/tmp/foo (master)$ 
```

cc @samdolt (crate author just to let you know, it's not your fault!)

**Comment by sgrif** [comment] 2018-07-10 17:41
As best I can tell, the crate also doesn't appear on S3 -- Which is odd since we do that upload before we commit to the index.

My suspicion is that this was caused by the server rebooting in the middle of processing this, after the index was updated, but before the database transaction was committed.

**Comment by Mark-Simulacrum** [comment] 2018-07-10 17:44
I asked @alexcrichton about this and it looks like the crate was uploaded and deleted from S3 in a ~5-10 minute window which leads me to believe that we reverted the upload due to a failed index push or something along those lines.

**Comment by carols10cents** [comment] 2018-07-10 18:53
This is a duplicate of https://github.com/rust-lang/crates.io/issues/1447

**Closed by carols10cents** 2018-07-10 18:53 UTC
