### ISSUE TITLE
Convert download chart from stacked chart to regular chart

### ISSUE THREAD

**Issue by jorgecarleitao** [rust-lang/crates.io#3876] opened 2021-08-31 11:09 UTC
**Describe the bug**

The plots showing the number of downloads do not respect the axis and are generally incorrect.

**To Reproduce**
1. Go to https://crates.io/crates/parquet2
2. Scroll down to the end of the page
3. unselect all versions except `0.1.0`
4. observe the values (essentially zero downloads last month)
5. select `0.2.0`
6. observe the values of `0.1.0` to reach the same values as `0.2.0`

**Expected behavior**
That the number of downloads in the label `0.1.0` is correctly represented

It seems that the values on `0.2.0` are being added to the ones from `0.1.0`. This is confusing because the tooltip for `0.1.0` shows `0` but the plot shows `300`. If it is cumulative, an idea would be write `>=0.2.0` instead of `0.2.0` on the legend?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac]
 - Browser [e.g. firefox]
 - Version [e.g. 91]

**Comment by Turbo87** [comment] 2021-08-31 11:22
> If it is cumulative

Yes, it is a stacked chart. In other words, it is intentionally working that way. The original implementation and intention behind this stacked chart predates my involvement though, and I've also already questioned how useful this representation is. I'm relabeling this as an enhancement though, since it currently works as intended.

**Comment by jorgecarleitao** [comment] 2021-08-31 14:34
Thanks @Turbo87 for the context. Imo there are good cases for both representations.

imo what is misleading in the current state is the label showing "0" while the axis shows `300` or something: imo either the label changes to `>=X.Y.Z`, or the axis changes (e.g. via non-stacked).

I would personally prefer two independent axis vertically stacked:

* the first one contains a single line with the number of downloads per day: that imo is the most useful to the broad audience as it shows the crates' popularity / usage.
* the second one shows the non-stacked version of the current plot: imo that is useful to creators to get an idea of which versions are being most used and how adoption of new versions is being made.

This IMO is the simplest way to address the "stacked is useful, non-stacked is also useful". A button to switch between the two versions instead of 2 plots would also work.

**Comment by billy1624** [comment] 2022-07-21 10:30
Hey @jorgecarleitao, I just came across this issue and I think your proposal is perfect: adding a button to toggle the chart display mode. I'd like to contribute and implementing it if crates.io team support such changes :)

**Comment by Turbo87** [comment] 2022-08-29 18:07
Resolved by https://github.com/rust-lang/crates.io/pull/5010. Thanks again @billy1624  :)

**Closed by Turbo87** 2022-08-29 18:07 UTC
Labels: C-enhancement, A-frontend

**Comment by billy1624** [comment] 2022-08-30 03:32
No problem! Glad to help :)
