### ISSUE TITLE
Description missing from crates page

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/crates.io#972] opened 2017-08-19 18:04 UTC
https://crates.io/crates/cbindgen is missing the description of the crate.

**Comment by kureuil** [comment] 2017-08-19 20:53
Probably a duplicate of https://github.com/rust-lang/crates.io/issues/967 the cbindgen crate doesn't seem to have any readme in their manifest.

**Comment by carols10cents** [comment] 2017-08-19 22:52
Yep, this is a duplicate of #967. Thanks!

**Closed by carols10cents** 2017-08-19 22:52 UTC
