### ISSUE TITLE
Page links on reverse dependencies seem to be broken

### ISSUE THREAD

**Issue by erickt** [rust-lang/crates.io#146] opened 2015-04-20 19:07 UTC
For example, on this [page](https://crates.io/crates/serde_macros/reverse_dependencies), while I can do to the next and previous links, I can't use the numbered links to get to a specific page.

**Comment by Turbo87** [comment] 2015-11-04 09:39
duplicate of #156 (or the other way around...)

**Comment by steveklabnik** [comment] 2015-11-04 09:41
The other one is newer, but it's referenced in that PR, so I'm going to taunt the flow of time and call this one the duplicate :wink:

**Closed by steveklabnik** 2015-11-04 09:41 UTC
