### ISSUE TITLE
Can't publish AGPL-3.0-or-later crate

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/crates.io#1278] opened 2018-03-25 05:16 UTC
Fails with `error: api errors: unknown license or other term: AGPL-3.0-or-later; see http://opensource.org/licenses for options, and http://spdx.org/licenses/ for their identifiers`, yet it is clearly listed on http://spdx.org/licenses/

**Comment by carols10cents** [comment] 2018-03-25 14:48
This is ultimately a duplicate of https://github.com/rust-lang/cargo/issues/4930 -- cargo and crates.io still use SPDX 2.4 and AGPL-3.0-or-later is SPDX 3.0.

The documentation for this has been improved but cargo's docs now ride the trains so the improvement has only made it to the beta cargo docs at https://doc.rust-lang.org/beta/cargo/reference/manifest.html#package-metadata.

**Comment by SoniEx2** [comment] 2018-03-25 15:20
So what do I use?

**Comment by wking** [comment] 2018-07-03 18:08
I've just pushed license-exprs v1.4.0 to crates.io with support for identifiers from the SPDX License List v3.1.  What's the procedure for bumping our dependencies.  I'd guess we want to bump this repo, and then, once that was live, update the Cargo docs and code?  Should we reopen this issue to track?  Get new issues?  An existing associated Cargo issue might be rust-lang/cargo#4930.

**Comment by carols10cents** [comment] 2018-07-04 16:00
Reopened! I'd love a PR that updates license-exprs!

**Comment by wking** [comment] 2018-07-10 01:39
> Reopened! I'd love a PR that updates license-exprs!

Filed as #1457.

**Closed** 2018-07-11 23:20 UTC

**Comment by carols10cents** [comment] 2018-07-12 02:33
The fix has been merged and deployed, thank you @wking !!!
