### ISSUE TITLE
Don't put crates whose name matches exactly at the top of search result lists

### ISSUE THREAD

**Issue by Gedweb** [rust-lang/crates.io#677] opened 2017-04-12 08:37 UTC
I want talk about of `Exact Match` in h1 tag.
It's looks like the piece of ... ads banner. This just unfairly for packages their created after somebody hold exact name.
When I type `http` I see this `0.0.0-prealpha Nov 21, 2014` - lolwut? This package is dead and we see it in top results. Where `Hyper` or some other alive project with community?

**Comment by carols10cents** [comment] 2017-04-12 12:50
What should we change? How should the styling be different? Or are you saying that we shouldn't put crates that are an exact match for the search query at the top?

**Comment by Gedweb** [comment] 2017-04-14 08:31
Don't show on top with special style. Most popular and helpful crates have not exact match names, an another example — `Serde`.It's can provide troubles for new user.

**Comment by carols10cents** [comment] 2017-04-14 14:48
It sounds like you're saying we shouldn't put crates that are an exact match for the search query at the top. We've had this functionality for a while, and while sometimes it isn't ideal, sometimes it might be exactly what you want. I'd like to leave this issue open for a little bit and see what people think, if other people like the exact match being first or not.

**Comment by Gedweb** [comment] 2017-04-24 08:19
Look, as one solution - check "stars" from github and sort by popularity. Also possible attach stars feature on cargo.io (own realisation)
This solution already used on [packagist.org](https://packagist.org/) (php libraries storage)

**Comment by carols10cents** [comment] 2017-08-02 15:47
We decided in rust-lang/rust#1824 not to change the ordering of search results; I'd like to see any proposed reordering of search results go through the RFC process.

**Comment by carols10cents** [comment] 2017-08-02 23:31
Actually I'm going to close this as a duplicate of #281.

**Closed by carols10cents** 2017-08-02 23:31 UTC
Labels: A-search, B-needs-rfc, C-feature-request
