### ISSUE TITLE
Timezone confusion in "Last Updated"

### ISSUE THREAD

**Issue by sfackler** [rust-lang/crates.io#1160] opened 2017-11-07 06:15 UTC
I'm in PST, so it seems like there's some UTC vs local time confusion somewhere.

![capture](https://user-images.githubusercontent.com/1455697/32479693-eddfb9fa-c33f-11e7-98f1-dcfeeef8a31b.PNG)

**Comment by carols10cents** [comment] 2017-11-07 15:49
Yep, we're working on it. Closing as a duplicate of https://github.com/rust-lang/crates.io/issues/1123.

**Closed by carols10cents** 2017-11-07 15:49 UTC
