### ISSUE TITLE
Dependencies list doesn't update correctly when going back

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/crates.io#461] opened 2016-10-21 15:36 UTC
Go to <https://crates.io/crates/derive-new>. Click on the link under Dependencies for `syn`. Then go back a page in your browser.  Look at the Dependencies list again: now it shows derive-new as a dependency of itself.

Reproduced in both Firefox 49 and Chromium 53.

**Comment by payload** [comment] 2016-10-27 20:22
Duplicate of https://github.com/rust-lang/crates.io/issues/444

**Comment by alexcrichton** [comment] 2016-10-27 23:09
Ah Thanks @payload!

**Closed by alexcrichton** 2016-10-27 23:09 UTC
