### ISSUE TITLE
error: failed to yank

### ISSUE THREAD

**Issue by Deedasmi** [rust-lang/crates.io#1296] opened 2018-03-29 20:05 UTC
Trying to yank a package today I got a 502 bad gateway. I only published the package a few moments before.

https://pastebin.com/4FqwzaL5

**Comment by Deedasmi** [comment] 2018-03-29 20:08
Just ran it again the the yank was successful. Going to leave the issue open though, since it was an actual error.

**Comment by jtgeibel** [comment] 2018-03-30 01:15
To me it looks like the error message is from nginx which is for some reason having an issue connecting to the backend.  What crate were you yanking?  That should help to track this down in the logs.

**Comment by jtgeibel** [comment] 2018-03-30 17:02
@carols10cents are you able to search the logs to see if there are any references to this?  I think you can search for `crates/rustup/0.1.0/yank`.

**Comment by carols10cents** [comment] 2018-03-31 18:21
Here's what I'm seeing in the logs for a search for `crates/rustup/0.1.0/yank`:

```
Mar 29 16:00:22 crates-io app/web.1: ERROR 2018-03-29T20:00:21Z: conduit_log_requests: 127.0.0.1:39606 [2018-03-29T20:00:21Z] Delete /api/v1/crates/rustup/0.1.0/yank - 30ms 500: entity not found No such file or directory (os error 2) 
Mar 29 16:00:22 crates-io heroku/router: at=info method=DELETE path="//api/v1/crates/rustup/0.1.0/yank" host=crates.io request_id=b5d46c83-c717-402d-8560-a719436616cb fwd="70.179.168.190" dyno=web.1 connect=0ms service=35ms status=502 bytes=356 protocol=https 
Mar 29 16:00:22 crates-io app/web.1: 2018/03/29 20:00:21 [error] 105#0: *228891 upstream prematurely closed connection while reading response header from upstream, client: 10.153.179.73, server: _, request: "DELETE //api/v1/crates/rustup/0.1.0/yank HTTP/1.1", upstream: "http://127.0.0.1:8888//api/v1/crates/rustup/0.1.0/yank", host: "crates.io" 
Mar 29 16:07:27 crates-io app/web.1:  INFO 2018-03-29T20:07:26Z: conduit_log_requests: 127.0.0.1:38764 [2018-03-29T20:07:26Z] Delete /api/v1/crates/rustup/0.1.0/yank - 2039ms 200 
Mar 29 16:07:27 crates-io heroku/router: at=info method=DELETE path="//api/v1/crates/rustup/0.1.0/yank" host=crates.io request_id=6f8cd220-a7d8-41a3-9d8c-358c0539d777 fwd="70.179.168.190" dyno=web.1 connect=0ms service=2045ms status=200 bytes=739 protocol=https 
```

The "no such file or directory" error is interesting. Given that you said you had only published the crate a few moments before, and that we have two heroku dynos with their own checkout of the git index, I wonder if the file it couldn't find was rustup's index file? That's my best guess for now but I don't have any evidence for that theory.

**Comment by jtgeibel** [comment] 2018-03-31 19:00
I had originally missed that the initial publish was shortly before the
yank. Yeah, I think you're onto something. The publish happened on one
Dyno, and the first yank hit the other repo, but the file inside that copy
of the index wasn't created yet.

If this was not the original publish, then something similar could happen
where the file existed but the commit adding the line for that version
hasn't been pulled down yet.

I think we can fix both issues by checking with GitHub that we have the
latest commits before performing any file operations within the index.

**Comment by sgrif** [comment] 2018-03-31 22:17
I can't imagine that "no such file or directory" would lead to a 502.

**Comment by jtgeibel** [comment] 2018-04-01 19:16
> I can't imagine that "no such file or directory" would lead to a 502.

That's an interesting observation.  It looks like that is the result of 2 additional bugs.  I've [patched civet](https://github.com/jtgeibel/rust-civet/commit/e05ce2ba9514b6ff394f358d08706bbe178caa08) so that the default handler explicitly returns an empty body with correct line endings.  We reverse proxy through nginx in production and I believe nginx wasn't happy with the LF instead of CRLF in this response.

The other issue is that we're even hitting this default handler at all.  I'm looking to add a middleware that will catch any `Err(_)` results and convert them into a 500 response with a JSON representation of the error.

**Comment by sgrif** [comment] 2018-05-03 21:36
I've spent a good chunk of the day looking into this, and I strongly agree with https://github.com/rust-lang/crates.io/issues/1296#issuecomment-377712934 as the cause. There's no other part of the code for that endpoint that could possibly fail with this error message. For that reason, I'm going to call this a duplicate of #1384, which discusses the underlying causes more in depth and is more directly actionable.

While we could improve our synchronous retry logic in the short term, that takes nearly as much work as just building a background queue for this, which we need to do eventually no matter what.

**Closed by sgrif** 2018-05-03 21:36 UTC
