### ISSUE TITLE
Date modified in the future

### ISSUE THREAD

**Issue by Cyborus04** [rust-lang/crates.io#4144] opened 2021-11-07 06:12 UTC
**Describe the bug**
The "time since modified" of the crate is negative minutes ago, or in the future

**To Reproduce**
Not sure, this is time sensitive, but if someone sees this within 30 mins of me submitting this, look at https://crates.io/crates/user_doc (the crate I noticed this on)

**Expected behavior**
The time modified be in the past, because it is

**Screenshots**
![Screenshot 2021-11-07 at 01-07-58 user_doc - crates io Rust Package Registry](https://user-images.githubusercontent.com/87248184/140634412-1bf075b8-5eed-4bce-909d-d4a880ce34ad.png)
5 minutes later...
![Screenshot 2021-11-07 at 01-07-52 user_doc - crates io Rust Package Registry](https://user-images.githubusercontent.com/87248184/140634415-a2af7624-5001-46e7-b384-2db0aa899945.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 94.0.1

**Comment by Cyborus04** [comment] 2021-11-07 06:30
Might be related to daylight savings time

**Comment by Turbo87** [comment] 2021-11-07 13:38
<img width="207" alt="Bildschirmfoto 2021-11-07 um 14 36 07" src="https://user-images.githubusercontent.com/141300/140647317-5211ae56-7179-4d84-a312-d976d491827f.png">
<img width="304" alt="Bildschirmfoto 2021-11-07 um 14 36 11" src="https://user-images.githubusercontent.com/141300/140647318-b7422428-8437-4a8c-befb-d0eaa30f4266.png">

It looks like on my side it's showing the right time and I'm not sure how to reproduce this. Are you sure that the clock on your machine was on the right time?

> Might be related to daylight savings time

that seems very likely, yes

**Comment by Cyborus04** [comment] 2021-11-07 15:15
I'm guessing either the person who published that update or the server made the time jump at a different time than I did

**Comment by Turbo87** [comment] 2021-11-07 15:32
we're using UTC timestamps everywhere, so daylight savings time shouldn't actually matter on the backend side 🤔

**Comment by Cyborus04** [comment] 2021-11-07 15:34
Yeah, I figured. But that's the only thing that had messed with my computer's time, it's otherwise correct

**Comment by Turbo87** [comment] 2021-12-28 21:27
I've failed to reproduce this unfortunately... 😞 

Since this is not really actionable without a working reproduction I'll close this issue for now. If someone finds the time to figure out a reproduction feel free to reopen :)

**Closed by Turbo87** 2021-12-28 21:27 UTC
Labels: C-bug, A-frontend
