### ISSUE TITLE
SyntaxError: expected expression, got '?'

### ISSUE THREAD

**Issue by 89z** [rust-lang/crates.io#2984] opened 2020-10-30 02:54 UTC
If I visit this page:

https://crates.io

I get this:

~~~
SyntaxError: expected expression, got '?'
~~~

and the page completely fails to load. Looks like the error comes from here:

https://crates.io/assets/vendor-88810d9ca9f516e55d105cd64a11cacc.js

and the prettified code:

~~~js
const t = Ember.Object.create({
   message: e.message,
   type: e.type || "info",
   autoClear: e.autoClear ?? n.autoClear ?? !1,
   clearDuration: e.clearDuration ?? n.clearDuration ?? 3200,
   onClick: e.onClick,
   htmlContent: e.htmlContent || !1,
   cssClasses: e.cssClasses
});
~~~

The issue is `??`:

https://developer.mozilla.org/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator#Implementation_Progress

That syntax has not been standardized, and does not work with my browser
(Waterfox 2020.10).

**Comment by a8nJ** [comment] 2020-10-30 03:38
Here is another approach, only an extra 30 characters:

~~~
const r = 'autoClear', s = 'clearDuration', t = Ember.Object.create({
   message: e.message,
   type: e.type || "info",
   [r]: !(r in e) ? !(r in n) ? !1 : n[r] : e[r],
   [s]: !(s in e) ? !(s in n) ? 3200 : n[s] : e[s],
   onClick: e.onClick,
   htmlContent: e.htmlContent || !1,
   cssClasses: e.cssClasses
});
~~~

**Comment by a8nJ** [comment] 2020-10-30 04:55
looks like this broke it https://github.com/rust-lang/crates.io/commit/f05fe126aa1ab61d0c1da5d8322d4092eb1a9fe5

**Comment by a8nJ** [comment] 2020-10-30 05:15
https://github.com/rust-lang/crates.io/pull/2926

**Comment by kentfredric** [comment] 2020-10-30 07:33
Just gotta say, its *really* terrible getting entirely blank pages due to bugs in poor backcompat, where you have to use a different browser to even see what the "contact support" options are.

Can yall do server-side rendering or something at some point? 

- Total unusability for a given is very bad ( this is where you are )
- Partial breakage would be less bad, but still undesirable ( if this can be achieved, please, ... )
- Lack of functional breakage but only cosmetic damage is tolerable and a laudable goal.

I understand doing compat is hard, but christ, "totally blank pages" is the worst failure mode I can imagine. Especially for a site that is primarily a form of documentation.

**Comment by kentfredric** [comment] 2020-10-30 07:40
And it looks like the Nullish operator is Firefox 72 (Jan 2020), Chrome 80 (Feb 2020), or Safari31.1 (May 2020) as a minimum. That's atrocious.

**Comment by Turbo87** [comment] 2020-10-30 10:44
> its _really_ terrible getting entirely blank pages due to bugs in poor backcompat, where you have to use a different browser to even see what the "contact support" options are.

I agree, this can certainly be improved.

> And it looks like the Nullish operator is Firefox 72 (Jan 2020), Chrome 80 (Feb 2020), or Safari31.1 (May 2020) as a minimum.

https://rust-lang.github.io/rfcs/1985-tiered-browser-support.html#supported-browsers specifies the current browser support policy for the Rust web resources, including crates.io.

AFAICT all of these browsers do support the feature in question, but maybe it's still a bit too restrictive. I'm not sure if we need an RFC to change the list of supported targets, but feel free to open a PR to change https://github.com/rust-lang/crates.io/blob/master/config/targets.js and we can discuss the proposed changes in there.

**Comment by Turbo87** [comment] 2020-10-30 13:28
> My browser is new

it might be that your WaterFox release is new, but it looks like Waterfox is quite out of sync with the mainline Firefox code, which is causing these issues.

one thing to consider is supporting the last two Firefox ESR releases instead of just the latest one. if Waterfox was based on the Firefix ESR releases then that might solve it.

**Comment by a8nJ** [comment] 2020-10-30 13:47
I think its reasonable to expect, that a users browser shouldnt be required to support experimental features just to load the page. So whatever changes need to me made here:

https://github.com/rust-lang/crates.io/blob/f0794b2b/config/targets.js

I would strongly suggest that be done.

**Comment by jtgeibel** [comment] 2020-10-30 14:29
> That's atrocious.

@kentfredric let's avoid phrasing like this please. I get that a blank page with no content is frustrating. If by chance the feature had slipped to Firefox 73 then it would not have been part of the ESR release and our toolchain would not have started using this syntax until July 2021. I think this just hit an edge case of our otherwise reasonable browser support matrix.

> experimental JavaScript features

@a8nJ I don't think this feature is experimental. ChackraCore (legacy Edge) appears to be the reason that the chart of implementation progress you linked above looks incomplete.

> one thing to consider is supporting the last two Firefox ESR releases instead of just the latest one

I think that sounds reasonable @Turbo87. Added to the agenda for us to discuss.

**Comment by a8nJ** [comment] 2020-10-30 14:52
@jtgeibel youre right its not experimental:

https://en.wikipedia.org/wiki/ECMAScript#11th_Edition_%E2%80%93_ECMAScript_2020

but its only been specified for 4 months. Do we really want to be in a situation where users are being presented with a blank screen, when their browser was released this month? Especially when the fix is so easy. All that needs to be done is either replace the `??` operators, or since Babel can transpile, then let it do that!

**Comment by jtgeibel** [comment] 2020-10-30 15:08
In the team meeting we reached consensus on changing to last 2 ESR and hope to have an updated build deployed later today. We plan to be more conservative than the official support policy, as long as this isn't a maintenance burden for the team (which it does not appear to be).

I've also bumped to next week's meeting to see if we can provide a better fallback.

**Comment by a8nJ** [comment] 2020-10-30 15:22
@jtgeibel thanks for doing that - I will try to check later today or tomorrow

From the surface - supporting 2 ESR seems extreme (even to me). But sadly thats not the case. Chrome and Firefox update furiously, to the point where ESR doesnt really mean what it used to. For example, the current ESR is 78, which only goes back to June of this year. The previous ESR is 68, which goes back to July 2019

**Comment by Turbo87** [comment] 2020-10-30 15:56
https://github.com/rust-lang/crates.io/pull/2985 should hopefully be able to fix this issue and gives our users enough time to update their browsers :)

**Comment by a8nJ** [comment] 2020-10-30 16:35
please reopen the issue...

It might need to be 2 years. For example, current Waterfox (2020.10) is based on
Firefox ESR 68, which is July 2019:

https://www.mozilla.org/en-US/firefox/68.0/releasenotes

**Comment by jtgeibel** [comment] 2020-10-30 16:43
#2985 is now deployed on production. We've confirmed that the transpiled output does not appear to use `??`. @a8nJ would you see if production works for you now?

**Comment by jtgeibel** [comment] 2020-10-30 16:51
I hadn't intended to close this. Our automation did based on the PR. This is already on the agenda for next week as well, so that we can discuss a better fallback. When JS is disabled we can at least show text explaining what happened. I'm not sure what our options are here.

**Comment by kentfredric** [comment] 2020-10-31 07:00
Please though, *do* consider SSR somewhere. It means if in future somebody has their browser JS broken, by whatever reason, they'll at least get some very dumb HTML that only partly works. Some of the functionality will be missing, sure, but they'll be at least able to get a basic set of information about crates. "Page loads, but is a bit weird with some things" is a much nicer problem to be faced with :)

**Comment by carols10cents** [comment] 2020-10-31 13:00
> Please though, _do_ consider SSR somewhere.

We have been considering server-side rendering through [Ember FastBoot](https://github.com/rust-lang/crates.io/issues/1811) or through an entire app rewrite, but it's a significant technical issue and we are a small volunteer team.

**Closed** 2020-12-24 17:21 UTC
Labels: C-bug
