### ISSUE TITLE
search links to most recent version *even* if that version was yanked

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/crates.io#595] opened 2017-03-06 13:58 UTC
Currently searching for "pandoc" on crates.io yields results that links to v0.5.3 of the `pandoc` crate.

But if you follow that link, you get the "This crate has been yanked" page.

Someone who wants to use the `pandoc` crate has to then go through the "view all versions" link to get to a non-yanked version.

It would be a better user experience if the search results linked to the most recent *non-yanked* version of a crate.

----

Note that this issue is somewhat distinct from #145 ; I read #145 as saying that if *all* versions of a crate have been yanked, then no entry should show up at all for it.

**Comment by carols10cents** [comment] 2017-03-06 15:51
Yes, I think this is a duplicate of #510 though.

**Closed by carols10cents** 2017-03-06 15:51 UTC
