### ISSUE TITLE
Can't log in (permission denied to access property "github-response" on cross-origin object)

### ISSUE THREAD

**Issue by willcassella** [rust-lang/crates.io#1404] opened 2018-05-30 04:25 UTC
I've (almost) never been able to log into crates.io. Currently, every time I click the 'log in with Github' button, a small browser window opens up, appears to begin loading crates.io, and then quickly disappears. Nothing else seems to change.

I've tried revoking the OAuth application from Github, clearing cookies, as well as logging out of Github before trying to log in from crates.io. I've also tested on Chrome/Firefox/Edge on Windows 10, as well as Firefox on Arch Linux. I've found [two](https://github.com/rust-lang/crates.io/issues/1077) [issues](https://github.com/rust-lang/crates.io/issues/1142) which appear similar to what I'm experiencing, but neither solution worked for me.

I first tried logging in a few months ago, then a few weeks ago, then today hoping it would randomly just work but it hasn't. I used OBS to record the window that pops up when I try to log in, but I can't find any similar issues on Google.

![Screenshot](http://pasteall.org/pic/show.php?id=e104e5a0a18f526fa05b86a85f3113e3)

I recently discovered that I can reliably log in from Firefox (safari) on my iPhone, but that doesn't seem to improve the desktop situation at all.

Any help would be appreciated, thanks!

**Comment by sgrif** [comment] 2018-05-30 19:52
Can you provide as many specific details about your environment as possible? (OS, exact browser version, etc)?

**Comment by carols10cents** [comment] 2018-05-30 19:59
I'm also interested in:

> clearing cookies

Was this github.com cookies, crates.io cookies, all cookies?

Is there anything different about the network you're on on your computer versus your phone? Such as ISP, firewalls, etc? Given that it's happening in all the browsers on your computer, I'm less inclined to think it's a browser or OS problem....

**Comment by jtgeibel** [comment] 2018-05-30 23:09
> Permission denied to access property "github_response" on cross-origin object

Given this message and the URL, it looks like this is related to the usage of `window.opener` in [github_authorize.js].  The popup is opened to a github domain, and then redirected back to us.  Perhaps some headers (like CORS) are being dropped somewhere causing modern browsers to treat the parent and child windows as different origins, even though at this point in the workflow they are both on the crates.io domain.

[github_authorize.js]: https://github.com/rust-lang/crates.io/blob/master/app/routes/github-authorize.js#L24-L31

**Comment by willcassella** [comment] 2018-06-10 18:13
> Can you provide as many specific details about your environment as possible?

Tested on the following (can't repro error message, but same behavior):
#### Windows 10 Pro 1709:
- Firefox 61.0b12 (64-bit)
- Chrome 67.0.3396.79 (64-bit)
- Edge 41.16299.402.0
#### Manjaro 17.1.10:
- Firefox 60.0.2 (64-bit)

> Was this github.com cookies, crates.io cookies, all cookies?

All cookies

I've tried on a few different networks (WiFi networks for computer, WiFi and cellular for phone), and it never works on my computer. Also recently it stopped working on my phone as well (Firefox for iOS and Safari for iOS).

**Comment by carols10cents** [comment] 2018-06-27 18:32
@willcassella I'm really sorry we haven't been able to figure this out yet :(

> Tested on the following (can't repro error message, but same behavior):

By this, do you mean you see a window pop up and then close, and nothing about the crates.io page changes? What happens if you reload the page at that point, are you logged in or no?

> Also recently it stopped working on my phone as well (Firefox for iOS and Safari for iOS).

That's really bizarre. Has anything changed with your phone since login was working?

**Comment by jtgeibel** [comment] 2018-06-27 23:07
> Wouldn't this cause login to fail for everyone though?

Yeah @carols10cents, it wasn't very clear from my original description, but I'm agreeing with your assessment that it could be network related.  That's what I meant by headers potentially being dropped, possibly by some middlebox.  I can't think of what else would cause this to show up cross-browser, cross-device, and cross-platform.

@willcassella are you on a corporate network that might be doing HTTPS interception?  Is there anything else unique about the network that you can think of?  You mentioned that on your phone you tried WiFi and cellular, but I'm not quite clear on if this now fails on your phone for both networks.

**Comment by willcassella** [comment] 2018-07-08 22:31
Back again!

> By this, do you mean you see a window pop up and then close, and nothing about the crates.io page changes? What happens if you reload the page at that point, are you logged in or no?

Manjaro is the only system where the pop-up lingers long enough that I can see grab a screenshot of it. Every other system it just sort of flashes in a then disappears. Refreshing the page doesn't change anything.

> are you on a corporate network that might be doing HTTPS interception?
I've tried on several networks (home WiFi, work WiFi, cellular) and it's always the same result. When it worked on my phone though it didn't seem to depend on the network.

**Comment by VersBinarii** [comment] 2019-02-06 14:20
Experiencing exactly the same issue on Firefox 66.0b5.
<img width="1669" alt="screen shot 2019-02-06 at 15 18 16" src="https://user-images.githubusercontent.com/2277121/52347609-a068fb00-2a22-11e9-9106-f14d82b5b848.png">

**Comment by jtgeibel** [comment] 2019-02-06 14:59
@VersBinarii thank you very much for the comment.  I'm not certain if the CSP issue is related (although it is something we should fix as well), however I have confirmed that it is not possible to login from www.crates.io (on Firefox stable).  I expect that his is actually restricted on the GitHub end, because the "homepage URL" doesn't match exactly as the domains are technically different.

As you said, we should be redirecting www to the apex domain.

**Comment by manifest** [comment] 2019-02-07 20:22
The same problem. Firefox 65.0 and Chrome 71.0.3578.98 (macOS Mojave). Any workaround for this one?

**Comment by jtgeibel** [comment] 2019-02-07 23:53
@willcassella and @manifest I'm wondering, do you have a valid email set in your GitHub profile?  We try to send an email on account creation if GitHub provides us with an email address, and if that address is invalid then it looks like we're failing the entire new user transaction.

**Comment by manifest** [comment] 2019-02-08 02:59
@jtgeibel yes, the problem was because of invalid public email in my profile. I've managed to log in. Thanks.

**Comment by VadneyK** [comment] 2021-05-21 00:09
I'm still experiencing this issue :(

**Comment by jtgeibel** [comment] 2021-05-21 03:40
Hi @VadneyK, would you provide additional details on the error message and your setup? What browser and version are you seeing this on, and have you tried with another browser? Is there any relevant output in the web console?

Also, it looks like we actually intended to close this when #1622 was deployed, but it would be worth double checking that you have a valid email address in GitHub.

I've checked the backend logs and I don't see any failed authorization requests in the last several days. I've also checked our Sentry reporting for the frontend and don't see anything that seems relevant there. Finally I've logged out and back in with no issue, so any additional information to help track this down would be really useful.

**Comment by jtgeibel** [comment] 2021-07-03 21:39
This should be closed by #1622.

**Closed by jtgeibel** 2021-07-03 21:39 UTC
Labels: A-accounts, C-bug

**Comment by akcgjc007** [comment] 2021-07-20 10:37
Facing the same issue in Chrome browser in Ubuntu.
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

```
Google Chrome | 91.0.4472.164 (Official Build) (64-bit)
```

**Comment by king-11** [comment] 2021-08-31 11:56
Facing this issue in Manjaro - Brave Browser

**Comment by sarkahn** [comment] 2021-09-01 03:38
Same, can't login on brave, but firefox works fine

**Comment by carols10cents** [comment] 2021-09-01 12:43
Hi, per [RFC 1985](https://rust-lang.github.io/rfcs/1985-tiered-browser-support.html), Brave is not one of the browsers we actively support. If someone wants to send in a pull request to fix Brave, we'll accept it, but the crates.io team doesn't have the bandwidth to fix it.

**Comment by carols10cents** [comment] 2021-09-01 12:44
Also, if you are experiencing this on a browser we do support, please open a new issue as this one is closed. Thanks!
