### ISSUE TITLE
Internal server error when trying to add GitHub team as owner after team or org rename

### ISSUE THREAD

**Issue by hannobraun** [rust-lang/crates.io#2687] opened 2020-08-13 11:28 UTC
Here's what I'm trying to do:
```
cargo owner --add github:braun-embedded:developers
```

This results in the following error message:
```
error: failed to invite owners to crate dw1000: failed to get a 200 OK response, got 500
headers:
        HTTP/2 500 

        content-length: 21

        server: nginx

        date: Thu, 13 Aug 2020 11:11:12 GMT

        strict-transport-security: max-age=31536000

        via: 1.1 vegur, 1.1 e56e6732f380db727425bac2d6158761.cloudfront.net (CloudFront)

        x-cache: Error from cloudfront

        x-amz-cf-pop: FRA2-C2

        x-amz-cf-id: csEF2IVenu_CJy_wWXX6wTUXObJaG0P_12nmvLGcT2uz9g_F0rdGhA==



body:
Internal Server Error
```

This error message is from the `dw1000` crate, but I've also tried the same on `dwm1001`, `embedded-timeout-macros`, and `ieee802154` before I gave up. So I think the problem is related to my user or the team, not those crates.

I've double checked the org name, team name, read the relevant documentation, and couldn't find any mistakes on my part. Of course I can't rule out that I'm doing something wrong, but the error message is less than helpful :-)

**Comment by jtgeibel** [comment] 2020-08-13 14:02
Hey @hannobraun, in the logs I'm seeing: `error="duplicate key value violates unique constraint "teams_github_id_key""`. It looks like the org was renamed. I've confirmed there is an existing row for `github:braun-robotics:developers` matching the `github_id` currently assigned to `github:braun-embedded:developers`. I've manually updated the row to match the new name.

This should be resolved, please let me know if you're still seeing an error.

Lets keep this issue open because we should add logic to detect and handle this automatically.

**Comment by hannobraun** [comment] 2020-08-14 08:47
Thank you for the quick reply, @jtgeibel! Indeed that was it. I've successfully added the team to two crates now.

**Closed** 2021-06-04 19:14 UTC
Labels: A-teams, C-bug
