### ISSUE TITLE
Published crate does not appear in "just updated" section

### ISSUE THREAD

**Issue by lfairy** [rust-lang/crates.io#949] opened 2017-08-11 09:49 UTC
I published two crates, [`maud_macros:0.17.1`](https://crates.io/crates/maud_macros/0.17.1) and [`maud:0.17.1`](https://crates.io/crates/maud/0.17.1), one after the other. Both of these uploads succeed.

But when I look for them on the front page of crates.io, only `maud` can be found:

![Screenshot of crates.io](https://user-images.githubusercontent.com/1572323/29208101-c2eb736c-7edc-11e7-8c6f-4a97c2ac69ae.png)

Indeed, the [underlying JSON data](https://gist.github.com/lfairy/bfddae44cf5e84b2d91c688d7aa4823c) doesn't include `maud_macros` at all!

I suspect that this is due to `maud_macros` having no keywords or categories in its metadata. The crate is supposed to be an implementation detail -- users should depend on `maud` instead -- so this lack of metadata is intentional. For that reason I'm not worried about it not appearing in the list 😛 It's still strange for crates.io to hide the entry though.

**Comment by carols10cents** [comment] 2017-08-11 14:32
> I suspect that this is due to maud_macros having no keywords or categories in its metadata.

What makes you suspect that? [This is the query that powers the "just updated" list](https://github.com/rust-lang/crates.io/blob/master/src/krate.rs#L1003-L1008), and it isn't filtering with anything to do with keywords or categories, so I don't see any evidence that that is the case.

This looks like a duplicate of #908 -- I looked in the database and the updated_at time for the maud_macros crate is still 2017-08-04. Because of the bug, if you don't happen to update any crate-level metadata, the crate's updated_at doesn't change :( 

I should be able to get the fix for this (#931) out soon.

**Closed by carols10cents** 2017-08-11 14:32 UTC
