### ISSUE TITLE
Images in rendered crate READMEs do not preserve aspect ratio

### ISSUE THREAD

**Issue by arzg** [rust-lang/crates.io#2732] opened 2020-08-30 12:21 UTC
Here’s a video demonstrating the issue and how to fix it (add `height: auto` to the images):

https://streamable.com/w26qlt

**Comment by arzg** [comment] 2020-08-30 12:23
_In case something goes wrong with the video._

Before the fix:

<img width="616" alt="Screen Shot 2020-08-30 at 10 22 12 pm" src="https://user-images.githubusercontent.com/31783266/91658863-42719c00-eb0f-11ea-930d-8f0de39f876a.png">

After the fix:

<img width="616" alt="Screen Shot 2020-08-30 at 10 22 59 pm" src="https://user-images.githubusercontent.com/31783266/91658887-5ddca700-eb0f-11ea-92df-9f0fa25b64e2.png">

**Comment by Turbo87** [comment] 2020-11-26 15:58
If you visit https://github.com/matklad/once_cell/blob/master/README.md, you can see that is has the exact same problem. This is caused by the README of that package having defined a fixed `height="300"` on the `<img>` and we are applying a `max-width: 100%` CSS style. 

Unfortunately your proposed fix is not working either because it would unconditionally override the `height="300"` attribute, which causes the image to grow higher than intended on large screens.

Since GitHub appears to suffer from the same issue, I'll close this issue for now since there does not seem to be much that we can do about this at the moment, unless someone comes up with an idea on how to solve this correctly.

**Closed by Turbo87** 2020-11-26 15:58 UTC
