### ISSUE TITLE
Display all available [features]

### ISSUE THREAD

**Issue by dancojocaru2000** [rust-lang/crates.io#1992] opened 2019-12-18 21:37 UTC
When looking at a crate on crates.io, it very much is guesswork finding out what the default features are and what features are available, and developers don't often make this obvious. 

As an example, for the `tungstenite` crate, if you want to use the function `tungstenite::client::connect`, you can see in the function documentation the following:

> The URL may be either ws:// or wss://. To support wss:// URLs, feature "tls" must be turned on.

There should be a more obvious way to find out about the "tls" feature, preferable on the crate's page on crates.io.

**Comment by carols10cents** [comment] 2019-12-19 15:24
Thanks! I'm actually going to close this as a duplicate of #465.

**Closed by carols10cents** 2019-12-19 15:24 UTC
