### ISSUE TITLE
Unable to load a page using HTTP GET Request (not via browser)

### ISSUE THREAD

**Issue by tomersein** [rust-lang/crates.io#4953] opened 2022-07-05 13:28 UTC
### Current Behavior

Hello,

I'm trying to get a page from https://crates.io/crates, specifically using the URL: https://crates.io/crates/regex/versions
I am using the header of Accept: text/html as a workaround of the 404 issue response, however I always get a static html page which contains the below error:

Sorry, it looks like we were not able to load the page. Please make sure your network connection works and you are using an up-to-date browser. If the issue persists, please visit our https://github.com/rust-lang/crates.io/issues/new/choose" issue tracker to report the problem.'

Can you please let me know if I am missing anything?

Thanks!

### Expected Behavior

Getting the static html page which I can see via browser.

### Environment

OS: windows

**Comment by Turbo87** [comment] 2022-07-05 14:44
> Can you please let me know if I am missing anything?

the page is currently only rendered client-side via javascript.

closing this as a duplicate of https://github.com/rust-lang/crates.io/issues/4783 and https://github.com/rust-lang/crates.io/issues/788 :)

**Closed by Turbo87** 2022-07-05 14:44 UTC
Labels: C-bug

**Comment by tatsuya6502** [comment] 2022-07-05 15:32
@tomersein — If you want to get the versions of regex crate, you can try to get this URL instead: https://crates.io/api/v1/crates/regex/versions and parse the returned JSON.

I do not know how to do this on Windows, but if on Linux or macOS, you can run the following commands on a terminal to parse the JSON response:

```console
$ curl -L https://crates.io/api/v1/crates/regex/versions | \
    jq -r '.versions[] | select( .yanked == false) | .num' | \
    sort --version-sort
0.1.0
0.1.1
...
1.5.5
1.5.6
```

**Comment by tomersein** [comment] 2022-07-10 07:25
Thanks!
