### ISSUE TITLE
Downloading crates from crates.io fails with HTTP 503 Application Error from herokucdn

### ISSUE THREAD

**Issue by Jolg42** [rust-lang/crates.io#6385] opened 2023-04-25 13:20 UTC
### Problem

Here is an example:

https://github.com/prisma/prisma-engines/actions/runs/4797771434/jobs/8535173263?pr=3917#step:4:1

```
Downloading crates ...
warning: spurious network error (2 tries remaining): failed to get successful HTTP response from `[https://crates.io/api/v1/crates/ahash/0.7.6/download`](https://crates.io/api/v1/crates/ahash/0.7.6/download%60), got 503
body:
<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>
```

Is there anything we can do on our side? (besides retrying)

https://status.crates.io/ does not mention any outage.

### Steps

- cargo clean && cargo build

**Comment by Turbo87** [comment] 2023-04-25 15:06
> A retry seems to work for now.

my best guess is that this happened while we were deploying and Heroku was restarting the dynos. this is obviously not a good excuse though. the long-term plan is to move away from Heroku and use proper zero downtime deployments, but unfortunately we haven't had time for that yet.

**Comment by Turbo87** [comment] 2024-02-12 11:35
since this issue was opened we've removed nginx from our server, which (in combination with the Heroku restart behavior) was the root cause for the majority of these issues. I'm going to close this issue since the primary issue should be resolved now :)

**Closed by Turbo87** 2024-02-12 11:35 UTC
Labels: A-infrastructure 📡
