### ISSUE TITLE
Wrong chart

### ISSUE THREAD

**Issue by hkcorac** [rust-lang/crates.io#1737] opened 2019-04-29 23:39 UTC
Hi,

I'm attaching a screenshot which shows wrong chart.

- Sample crate: <https://crates.io/crates/vector2math>
- Release date of v0.5.0: April 30, 2019
- Some day in March shows that v0.5.0 was downloaded 11 times.

Thank you,

![the-wrong-chart](https://user-images.githubusercontent.com/48109489/56933583-abf42b80-6b12-11e9-920f-4b51b0bf470b.png)

**Comment by sgrif** [comment] 2019-05-07 19:05
Duplicate of #1704

**Closed by sgrif** 2019-05-07 19:05 UTC
