### ISSUE TITLE
Show latest non-yanked version (if any)

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/crates.io#217] opened 2015-11-18 16:39 UTC
`/crates/<name>` (without a version number) should show the latest version of the crate *that is not yanked* (if any).

For example:

* The latest publish version of `url` was 0.2.37
* A number of changes were merged in the git repo since, including one breaking change
* I published 0.3.0
* Then I realized that the breaking change was incorrect. I reverted the commit, and ran `cargo yank --vers 0.3.0`
* I published 0.2.38 for the other changes

Now https://crates.io/crates/url shows 0.3.0 with "This crate has been yanked". It should show 0.2.28 instead.

**Comment by alexcrichton** [comment] 2015-11-18 17:38
I believe this is a dupe of https://github.com/rust-lang/crates.io/issues/76, so closing in favor of that.

**Closed by alexcrichton** 2015-11-18 17:38 UTC

**Comment by SimonSapin** [comment] 2015-11-18 19:34
Ah, I didn't realise that `max_version` was what I was looking for. Sorry for the duplicate!
