### ISSUE TITLE
failed to yank

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/crates.io#1591] opened 2019-01-10 06:36 UTC
```
$ cargo +stable yank --vers 0.6.4
    Updating crates.io index
        Yank fake-rand-test:0.6.4                                                                                                                                                    
error: failed to yank

Caused by:
  failed to get a 200 OK response, got 500
headers:
	HTTP/1.1 500 Internal Server Error

	Connection: keep-alive

	Server: nginx

	Date: Thu, 10 Jan 2019 06:36:18 GMT

	Content-Length: 21

	Strict-Transport-Security: max-age=31536000

	Via: 1.1 vegur

	

body:
Internal Server Error
```

**Comment by sgrif** [comment] 2019-01-10 22:33
Can you give a rough time of when this happened? I have no records of any 500 responses in the past 24 hours

**Comment by jethrogb** [comment] 2019-01-11 04:55
I tried it multiple times. It happened around the time I filed the PR, so Jan 10 06:06~06:36 UTC. It worked fine just now.

**Comment by sgrif** [comment] 2019-01-11 15:52
For anyone else looking into this, request ids for the failed requests are:

- `e79aa68a-14e4-404c-a0f2-e9d63e18a649`
- `f575ff4d-63d2-4bd0-8ee0-8dba26676c69`

**Comment by sgrif** [comment] 2019-01-11 16:10
Here's the timeline of events and root cause:

- At 06:33 the crate `fake-rand-test` was published. The request was processed by `web.2`
- At 06:35 and 06:36 requests to yank the crate were received by `web.1`.
- No requests that affected the index were received by `web.1` that would have caused a pull of the index, so the file for this crate was not present.
- An error was returned by https://github.com/rust-lang/crates.io/blob/d9122dabf6667e56e37dd2dc6a698eefe079374d/src/git.rs#L87 when the file was not found.

The way index updates work today is that we modify the index locally, try to commit and push, and if that fails, do `git fetch && git reset --hard` and try again. However, the code today assumes that the file system operations will succeed, and does not pull the index if those fail. 

This will be fixed by #1588

**Comment by hellow554** [comment] 2019-02-11 07:00
Why is this closed when the patch hasn't merged yet? 🤔 

This happend to me today as well, I guess it's the same error:

```
$ cargo yank --vers 0.1.0
    Updating registry `https://github.com/rust-lang/crates.io-index`
        Yank doctest_aksjdlasjkdlajskdjasld:0.1.0
error: failed to yank: failed to get a 200 OK response, got 500
headers:
    HTTP/1.1 500 Internal Server Error

    Connection: keep-alive

    Server: nginx

    Date: Mon, 11 Feb 2019 06:57:06 GMT

    Content-Length: 21

    Strict-Transport-Security: max-age=31536000

    Via: 1.1 vegur

    

body:
Internal Server Error
```

**Comment by sgrif** [comment] 2019-02-11 07:10
At the time I closed it I didn't yet know we had more work to do on the fix before it could be merged. Will leave this open so folks know that we are aware of the issue and working on it.

In the mean time, if you have a version that you need to yank/unyank and are unable to do so please email help@crates.io and we'll take care of it.

**Comment by hellow554** [comment] 2019-02-11 07:11
It worked for me the second time I tried it. 
You could use one of the [github keywords](https://help.github.com/articles/closing-issues-using-keywords/) to automatically close the issue ;)

**Closed** 2019-03-09 01:51 UTC
