### ISSUE TITLE
Creating A crates.io Account On Brave Failing

### ISSUE THREAD

**Issue by Shri333** [rust-lang/crates.io#4863] opened 2022-06-03 19:45 UTC
### Current Behavior

When I tried to create a crates.io account (i.e. give crates.io the appropriate permissions in my Github account), a tab asking to authorize crates.io on Github immediately opened and then closed. Clearing cookies did not help. I had to switch to Safari to register. Then, I was able to sign in normally on Brave.

### Expected Behavior

The tab should stay open, so that I can authorize crates.io with the appropriate Github permissions.

### Steps To Reproduce

1. Go to crates.io
2. Click log in with Github (only works with accounts that have not given permission to crates.io yet)

### Environment

- Browser: Brave [Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (arm64)]
- OS: macOS 12.4
- Device: M1 Macbook Air (2020)

**Comment by JohnTitor** [comment] 2022-06-04 01:00
I cannot reproduce it on my env, is there any extension you've installed?

**Comment by JohnTitor** [comment] 2022-06-04 01:08
I think this is a duplicate of #4575 and #4176

@Shri333 If you have any information related to the bug, feel free to post it on the above issue, thanks!

**Closed by JohnTitor** 2022-06-04 01:08 UTC
Labels: C-bug, B-needs-investigation
