### ISSUE TITLE
Show list of crate features

### ISSUE THREAD

**Issue by baoyachi** [rust-lang/crates.io#3355] opened 2021-03-01 09:38 UTC
![image](https://user-images.githubusercontent.com/10433001/109478859-bab41c80-7ab4-11eb-89e0-281ec98592d3.png)
 
add features with website,that can quick preview. for example with tokio features:

```toml
[features]
default = []
fs = []
full = ["fs", "io-util", "io-std", "macros", "net", "parking_lot", "process", "rt", "rt-multi-thread", "signal", "sync", "time"]
io-std = []
io-util = ["memchr", "bytes"]
macros = ["tokio-macros"]
net = ["libc", "mio/os-poll", "mio/os-util", "mio/tcp", "mio/udp", "mio/uds"]
process = ["bytes", "once_cell", "libc", "mio/os-poll", "mio/os-util", "mio/uds", "signal-hook-registry", "winapi/threadpoollegacyapiset"]
rt = []
rt-multi-thread = ["num_cpus", "rt"]
signal = ["once_cell", "libc", "mio/os-poll", "mio/uds", "mio/os-util", "signal-hook-registry", "winapi/consoleapi"]
sync = []
test-util = []
time = []
[target."cfg(loom)".dev-dependencies.loom]
version = "0.4"
features = ["futures", "checkpoint"]
[target."cfg(tokio_unstable)".dependencies.tracing]
version = "0.1.21"
features = ["std"]
optional = true
default-features = false
[target."cfg(unix)".dependencies.libc]
version = "0.2.42"
optional = true
```

**Comment by jhpratt** [comment] 2021-03-26 05:10
If this happens, please let there be some way to declare that a feature should be be relied upon externally.

**Comment by AngelicosPhosphoros** [comment] 2021-04-19 19:34
@jhpratt 
>should not be relied upon externally

What you mean?

**Comment by jhpratt** [comment] 2021-04-19 23:11
Sometimes there are features like `__docsrs` that aren't intended to be used by end users, only in CI and on docs.rs. It would be best to avoid displaying these features imo.

**Comment by Turbo87** [comment] 2021-12-23 01:34
closing this as a duplicate of https://github.com/rust-lang/crates.io/issues/465

**Closed by Turbo87** 2021-12-23 01:34 UTC
Labels: C-enhancement, A-frontend
