### ISSUE TITLE
README not loading

### ISSUE THREAD

**Issue by dns2utf8** [rust-lang/crates.io#2435] opened 2020-04-17 10:40 UTC
Hi all

I implemented the [sudo crate](https://crates.io/crates/sudo/) that was name-squatted in the past.
For some reason the README does not render. I tried to dig into the reason and learned that the rendering has been offloaded to some other system.

It looks to me as if that system does not complete the task for some reason:
https://static.crates.io/readmes/sudo/sudo-0.3.0.html

I am not sure if this is the place to report the issue and I am curious which project actually renders the readme.

Cheers,
Stefan

**Comment by dns2utf8** [comment] 2020-04-17 10:45
For the record, accessing the README's URL yields this error:

![image](https://user-images.githubusercontent.com/739070/79561261-91ef8800-8098-11ea-8cdd-7d3a5e0adecf.png)

**Comment by Turbo87** [comment] 2020-04-17 10:56
@jtgeibel any ideas? it looks like the frontend is trying to do the corresponding network requests but the call to https://static.crates.io/readmes/sudo/sudo-0.3.0.html fails with status `403 Forbidden`

**Comment by JohnTitor** [comment] 2020-04-17 10:58
It seems the Cargo.toml doesn't have the readme section?

**Comment by Turbo87** [comment] 2020-04-17 11:02
hmm, I'm surprised we don't default to `README.md` for this 🤔 

do you know if there is a reason for the decision?

**Comment by dns2utf8** [comment] 2020-04-17 11:33
> It seems the Cargo.toml doesn't have the readme field?: https://doc.rust-lang.org/cargo/reference/manifest.html#the-readme-field

I totally forgot to add the field. I did check it with `cargo package` to fill the required fields.

Checking for the default `README.md` or `README.rst` looks like one option.

Another idea I just had, what if there was a test render?
Maybe something like `cargo crates-io-preview` for local render?

Or that the UI on crates.io could display a small warning once the package is published?

**Comment by JohnTitor** [comment] 2020-04-17 11:54
> hmm, I'm surprised we don't default to README.md for this thinking
>
> do you know if there is a reason for the decision?

I'm not sure and may be missing something but I think there's no way not to display README currently if it's by default (though I believe most people want to display it :P).

**Comment by dns2utf8** [comment] 2020-04-17 12:05
Another idea, what if `cargo package` had a `--polish` flag that would warn the user if the "nice to have" fields are missing?

**Comment by Turbo87** [comment] 2020-04-19 07:30
since the root cause of the issue has been discovered to be the missing toml file setting, I'm closing this issue. we can still discuss options to improve the situation, but the original issue seems resolved now.

**Closed** 2020-04-19 07:30 UTC

**Comment by dns2utf8** [comment] 2020-04-19 10:15
I looked into the code to see if I can implement the nice default.
However, I am unable to find the code actually generating the HTML.
It looks like it has been moved out of this crate.
Do you know where it has been moved to?

**Comment by Turbo87** [comment] 2020-04-19 10:18
unfortunately, I personally don't. @jtgeibel  @JohnTitor any idea?
