### ISSUE TITLE
Display yank reason once you can provide one via cargo

### ISSUE THREAD

**Issue by colindean** [rust-lang/crates.io#1153] opened 2017-10-30 15:24 UTC
I learned about `rustfmt` today and learned that it has cargo integration to enable `cargo fmt`. I searched cargo from the command line and got this output:

```
± (master *%) $ cargo search rustfmt
    Updating registry `https://github.com/rust-lang/crates.io-index`
rustfmt = "0.9.0"             # Tool to find and fix Rust formatting issues
rustfmt-nightly = "0.2.13"    # Tool to find and fix Rust formatting issues
rfmt = "0.1.0"                # Another Rust source code formatter.
scout = "1.1.0"               # Small fuzzy finder for the command line
cargo-make = "0.7.3"          # Rust task runner and build tool.
bcc-sys = "0.3.1"             # Rust binding to BPF Compiler Collection (BCC)
cargo-fmt = "0.1.0"           # Allows `rustfmt` to be called through `cargo`
imgui = "0.0.16"              # High-level Rust bindings to dear imgui
harbor = "0.1.0"              # Project manager for CoreOS fleets.
aries = "0.1.0"               # a web framwork for rust-lang.
... and 29 crates more (use --limit N to see more)
```

Ah ha! `cargo-fmt` is what I want, right? RIGHT?

```
± (master *%) $ cargo install cargo-fmt
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: could not find `cargo-fmt` in `registry https://github.com/rust-lang/crates.io-index`
```

That's odd, it just showed up in the search!

I resort to the browser: https://crates.io/crates/cargo-fmt

<img width="795" alt="screen shot 2017-10-30 at 10 59 10 am" src="https://user-images.githubusercontent.com/197224/32177726-67382b8c-bd61-11e7-9e59-33871c0f86a9.png">

Yanked. I think what I want is `rustfmt`. I installed it, and sure enough:

```
  Installing /Users/colin/.cargo/bin/cargo-fmt
  Installing /Users/colin/.cargo/bin/rustfmt
```

I think my confusion could be avoided by:

1. Convey in `cargo search` results that a package has been yanked. Maybe by highlighting the name in an ANSI color and outputting a colored message at the bottom that says something like "Packages in yellow have been yanked and are not directly installable. See https://somewhere.else for more information."
1. Have the crate page for `cargo-fmt` have some kind of text explaining _why_ it was yanked and perhaps suggesting a next step (e.g. "Package `X` has superseded this package" or "This package was erroneously published" or something like that).

That second one is probably the task for crates.io to tackle, although [searching through the cargo repo for "yanked" shows](https://github.com/rust-lang/cargo/search?q=yanked&type=Issues&utf8=%E2%9C%93) that I'm not the first person to encounter a problem like this:

1. [Start requiring a reason for all yanks #2608](https://github.com/rust-lang/cargo/issues/2608)
1. [Mismatch against yanked version doesn't inform user about yank #4260](https://github.com/rust-lang/cargo/issues/4260)

I think I'm going to file a similar issue with cargo since there's potentially work to be done there, too.

**Comment by carols10cents** [comment] 2018-06-28 16:47
1. is a duplicate of https://github.com/rust-lang/crates.io/issues/145 as far as the crates.io side, and then your rust-lang/cargo#4679 would cover displaying the yanked info in the results of `cargo search` (that change would need to be made in cargo).

I'm going to leave this issue open for crates.io displaying a yank reason to go with rust-lang/cargo#2608.

**Comment by Turbo87** [comment] 2020-06-12 13:12
since https://github.com/rust-lang/cargo/issues/2608 does not seem to have any movement I'm going to close this issue for now. should such a mechanism ever be implemented in cargo we can reopen the issue :)

**Closed by Turbo87** 2020-06-12 13:12 UTC
Labels: A-frontend, A-interaction-with-cargo, A-yank, C-feature-request
