### ISSUE TITLE
Provide UI to allow searching within categories

### ISSUE THREAD

**Issue by therealprof** [rust-lang/crates.io#1626] opened 2019-02-14 19:38 UTC
In embedded we often have the strong desire that we'd like to narrow searches to the `no_std` category. At the RaH @sgrif mentioned that the backend already allows narrowing down searches but this is currently not exposed in the user interface.

Providing a user interface to allow this would be a *huge* usability improvement for us.

**Comment by erlend-sh** [comment] 2019-02-18 17:39
Agreed!

On an administrative note, either #491 should be closed and link here or this issue should be closed as a duplicate.

**Comment by carols10cents** [comment] 2019-02-19 14:26
Yep, I think this is a duplicate of #491. Closing, thanks!

**Closed by carols10cents** 2019-02-19 14:26 UTC
