### ISSUE TITLE
Keep getting 206 response on some crates when building from GH Actions / Azure

### ISSUE THREAD

**Issue by tomtau** [rust-lang/crates.io#2771] opened 2020-09-11 04:19 UTC
e.g. 
```
error: failed to download from `https://crates.io/api/v1/crates/zxcvbn/2.0.1/download`	

	Caused by:
	  failed to get 200 response from `https://static.crates.io/crates/zxcvbn/zxcvbn-2.0.1.crate`, got 206
```

**Comment by carols10cents** [comment] 2020-09-11 13:00
We're aware of this issue-- it's a problem with AWS and we're working with them to resolve it. https://github.com/rust-lang/cargo/issues/8647 has more info; I'm closing this as a duplicate of that issue. Thanks!

**Closed by carols10cents** 2020-09-11 13:00 UTC
