### ISSUE TITLE
Render Reference Links

### ISSUE THREAD

**Issue by dbrgn** [rust-lang/crates.io#1007] opened 2017-08-24 07:07 UTC
I hope this hasn't already been reported (I searched the issues for this bug), but it seems that reference links in README files are broken: https://crates.io/crates/threema-gateway

E.g. this line:

    [![Travis CI][travis-ci-badge]][travis-ci]

...has the following link reference definitions at the bottom of the README.

    [travis-ci]: https://travis-ci.org/dbrgn/threema-gateway-rs
    [travis-ci-badge]: https://img.shields.io/travis/dbrgn/threema-gateway-rs.svg?maxAge=300 

But they aren't rendered.

Here's the spec: http://spec.commonmark.org/0.27/#reference-link

**Comment by kureuil** [comment] 2017-08-24 16:09
This seems to be a duplicate of https://github.com/rust-lang/crates.io/issues/966, the markdown parser we're currently using is having trouble with these links in images.

Should be fixed when https://github.com/rust-lang/crates.io/pull/981 will be merged.

**Comment by carols10cents** [comment] 2017-08-25 19:04
Closing as duplicate of #966.

**Closed by carols10cents** 2017-08-25 19:04 UTC
Labels: A-readme, C-bug
