### ISSUE TITLE
Fix build metadata handling in SemVer versions

### ISSUE THREAD

**Issue by sdroege** [rust-lang/crates.io#6451] opened 2023-05-08 12:19 UTC
### Current Behavior

Currently there's apparently not checking. Yesterday https://crates.io/crates/const_fn_assert was updated with a new version, and apparently `cargo` does not like the checksum of that crate and reports

```
error: failed to sync
Caused by:
  failed to download packages
Caused by:
  failed to verify the checksum of `const_fn_assert v0.1.2+deprecated`
```

### Expected Behavior

This ideally should've been caught before accepting the new version. `cargo` itself checks this before uploading AFAIU, so I kind of assume that this was done intentionally and manually to "deprecate" this crate a bit harder.

### Steps To Reproduce

1. `cargo init`
2. `cargo add const_fn_assert`
3. `cargo check`

```
  Downloaded const_fn_assert v0.1.2+deprecated
error: failed to verify the checksum of `const_fn_assert v0.1.2+deprecated`
```

**Comment by Turbo87** [comment] 2023-05-08 12:22
https://github.com/rust-lang/crates.io/blob/127ac545cfe7885f68bd4c2b53265079360774d6/src/controllers/krate/publish.rs#L190 suggests that we calculate the checksum ourself, so I'm quite curious now what went wrong with that publish 🤔

**Comment by Turbo87** [comment] 2023-05-08 12:27
I think the problem here is how "build metadata" in the `version` field is handled. You can see at https://crates.io/crates/const_fn_assert/versions that crates.io now has `0.1.2` and `0.1.2+deprecated`. crates.io currently treats them as different versions (for no good reason IMHO), and I assume cargo ignores the build metadata and downloads a different crate file that does not correspond to the build metadata.

/cc @rust-lang/cargo

**Comment by sdroege** [comment] 2023-05-08 12:29
Ah that would make sense and would at least be an honest mistake. Thanks for checking this so fast :)

**Comment by epage** [comment] 2023-05-08 12:35
rust-lang/cargo#11412 for where the cargo team has discussed this

**Comment by epage** [comment] 2023-05-08 12:36
Ah, that pointed me to this being a dupe of rust-lang/crates.io#1059

**Comment by Turbo87** [comment] 2023-05-08 13:03
for cross-referencing: we discussed the situation on Zulip (see https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/const_fn_assert/near/356688583)

we decided to remove `const_fn_assert#0.1.2+deprecated` from crates.io since our backend shouldn't have accepted the publish in the first place. I've also sent an email to the crate owner explaining the situation.

since we already have https://github.com/rust-lang/crates.io/issues/1059 for tracking the problem I'll go ahead and close this issue here since the `const_fn_assert` situation itself has been resolved AFAICT.

**Closed by Turbo87** 2023-05-08 13:03 UTC
Labels: C-bug 🐞, A-backend ⚙️

**Comment by Turbo87** [comment] 2023-05-30 10:54
https://github.com/rust-lang/crates.io/pull/6518 has now been deployed. in other words: crates.io no longer allows "publishes with versions only differing in metadata"
